// Olympus tutorial 04, Choosing registers and bits: the Algorithm 1 explorer.
// DATA: three real site islands (DeepGEMM k512 c.tile_done and SYNCS.EXCH.64, t1_softmax LDGSTS), extracted
// CPU-only from the search planner at commit 40a887a (the final pass's planner, before the module renames of
// DECISIONS 92): template, values, dependency edges and latencies per register assignment, the cost of every
// valid order, the exact / greedy / optimal orders, the logged DFS events with their work units, the scoreboards.
(function () {
  'use strict';

  const reduceMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  const NS = 'http://www.w3.org/2000/svg';
  const $ = (sel, el) => (el || document).querySelector(sel);
  const $$ = (sel, el) => Array.from((el || document).querySelectorAll(sel));
  const bi = (en, zh) => `<span lang="en">${en}</span><span lang="zh-CN">${zh}</span>`;
  const num = (x) => x.toLocaleString('en-US');
  const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
  const A64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
  const BUDGET = 5000;                     // search.WORK_BUDGET

  function S(tag, attrs, parent, text) {
    const e = document.createElementNS(NS, tag);
    if (attrs) for (const k in attrs) e.setAttribute(k, attrs[k]);
    if (text != null) e.textContent = text;
    if (parent) parent.appendChild(e);
    return e;
  }
  // an SVG <text> with an English and a Chinese <tspan> (site.css hides the other [lang])
  function ST(parent, attrs, en, zh) {
    const t = S('text', attrs, parent);
    S('tspan', { lang: 'en' }, t, en);
    S('tspan', { lang: 'zh-CN' }, t, zh == null ? en : zh);
    return t;
  }

  // one floating tooltip (widgets.css .tip)
  const tip = document.createElement('div');
  tip.className = 'tip';
  tip.hidden = true;
  document.body.appendChild(tip);
  function showTip(html, ev) {
    tip.innerHTML = html;
    tip.hidden = false;
    const r = tip.getBoundingClientRect();
    let x = ev.clientX + 14, y = ev.clientY + 14;
    if (x + r.width > window.innerWidth - 8) x = ev.clientX - r.width - 14;
    if (y + r.height > window.innerHeight - 8) y = ev.clientY - r.height - 14;
    tip.style.left = Math.max(8, x) + 'px';
    tip.style.top = Math.max(8, y) + 'px';
  }
  const hideTip = () => { tip.hidden = true; };
  function tipOn(el, html) {
    el.addEventListener('mouseenter', (ev) => showTip(typeof html === 'function' ? html() : html, ev));
    el.addEventListener('mousemove', (ev) => showTip(tip.innerHTML, ev));
    el.addEventListener('mouseleave', hideTip);
  }

  const DATA = {"sites":{"tile":{"case":"t3_dg_1d2d_k512","set":"trace-pp","before":1100,"label":"c.tile_done","kind":"ts","form":"elect","tmpl":["CS2R.32 R4, SR_CLOCKLO","LEA.LO R4, PT, R4, 0x14, 0x6","ELECT P0, URZ, ~URZ","ULOP3.LUT UPT, UR0, UR62, 0x3f, URZ, 0xc0, !UPT","UIMAD.WIDE.U32 {UR0,UR1}, UPT, UR0, 0x4, {UR60,UR61}","@P0 STG.E [RZ+UR0+0x20], R4","UIADD3 UR62, UPT, UPT, UR62, 0x1, URZ"],"values":[{"f":"R","n":1,"canon":4,"d":0,"uses":[1]},{"f":"R","n":1,"canon":4,"d":1,"uses":[5]},{"f":"P","n":1,"canon":0,"d":2,"uses":[5]},{"f":"UR","n":1,"canon":0,"d":3,"uses":[4]},{"f":"UR","n":2,"canon":0,"d":4,"uses":[5]}],"preds":[[],[0],[],[],[3],[1,2,4],[3]],"raw":[[1],[5],[5],[4],[5],[],[]],"norders":150,"vars":[{"part":[[0,1],[2],[3,4]],"body":["CS2R.32 R4, SR_CLOCKLO","LEA.LO R4, PT, R4, 0x14, 0x6","ELECT P0, URZ, ~URZ","ULOP3.LUT UPT, UR0, UR62, 0x3f, URZ, 0xc0, !UPT","UIMAD.WIDE.U32 {UR0,UR1}, UPT, UR0, 0x4, {UR60,UR61}","@P0 STG.E [RZ+UR0+0x20], R4","UIADD3 UR62, UPT, UPT, UR62, 0x1, URZ"],"need":[0,1,0,0,8,22,8],"edges":[[0,1,4,"fix"],[0,5,4,"fix"],[1,5,4,"fix"],[2,5,13,"fix"],[3,4,4,"fix"],[3,5,12,"fix"],[3,6,1,"fix"],[4,5,8,"fix"]],"rel":[30,30,30,30,30,14,30],"claim":[0,0,0,0,0,1,0],"root":28,"greedy":[2,3,0,4,1,5,6],"n":150,"cmin":28,"c":"FFFGGGKKLHKEEEBBBBBBBBFFFGGHGHCCCCCCCCHHIGGGIHFGDDHGFFFBBCBBBBBCCDAAACABBBCDABGGGHHIHICCCCCCCCGGHFFFHGGHDDGFCCDBBBCBBBBBDBBKKLGGGKHFFFFLHGHIDDHFDCCKGF"},{"part":[[0],[1],[2],[3],[4]],"body":["CS2R.32 R9, SR_CLOCKLO","LEA.LO R10, PT, R9, 0x14, 0x6","ELECT P3, URZ, ~URZ","ULOP3.LUT UPT, UR10, UR62, 0x3f, URZ, 0xc0, !UPT","UIMAD.WIDE.U32 {UR2,UR3}, UPT, UR10, 0x4, {UR60,UR61}","@P3 STG.E [RZ+UR2+0x20], R10","UIADD3 UR62, UPT, UPT, UR62, 0x1, URZ"],"need":[0,1,0,0,8,22,8],"edges":[[0,1,4,"fix"],[1,5,4,"fix"],[2,5,13,"fix"],[3,4,4,"fix"],[3,6,1,"fix"],[4,5,8,"fix"]],"rel":[30,30,30,30,30,14,30],"claim":[0,0,0,0,0,1,0],"root":28,"greedy":[2,3,0,4,1,5,6],"n":150,"cmin":28,"c":"FFFGGGKKLHKEEEBBBBBBBBFFFGGHGHCCCCCCCCHHIGGGIHFGDDHGFFFBBCBBBBBCCDAAACABBBCDABGGGHHIHICCCCCCCCGGHFFFHGGHDDGFCCDBBBCBBBBBDBBKKLGGGKHFFFFLHGHIDDHFDCCKGF"}],"named":{"exact":{"v":0,"order":[2,3,0,6,4,1,5],"cost":28},"greedy":{"v":0,"order":[2,3,0,4,1,5,6],"cost":28},"best":{"v":0,"order":[2,3,0,6,4,1,5],"cost":28}},"events":[["start","greedy",0,3507,null,null,null,null,null,6945],["node","greedy",0,3537,[],null,null,null,null,null],["node","greedy",0,3567,[2],null,null,null,null,null],["node","greedy",0,3597,[2,3],null,null,null,null,null],["node","greedy",0,3627,[2,3,0],null,null,null,null,null],["node","greedy",0,3657,[2,3,0,4],null,null,null,null,null],["node","greedy",0,3687,[2,3,0,4,1],null,null,null,null,null],["node","greedy",0,3717,[2,3,0,4,1,5],null,null,null,null,null],["leaf","greedy",0,3847,[2,3,0,4,1,5,6],null,null,28,true,null],["end","greedy",0,3847,null,null,28,null,null,null],["start","greedy",1,3877,null,null,28,null,null,6945],["node","greedy",1,3907,[],null,28,null,null,null],["prune","greedy",1,3937,[2],28,28,null,null,null],["end","greedy",1,3937,null,null,28,null,null,null]],"w0":1945,"rep":{"search_ms":1.981,"dfs_nodes":10,"pruned":1,"proven":true,"capped_in":null,"work":1992,"free_sb":[2,3,4,5],"kernel_busy_sb":[0,1],"free":{"R":151,"UR":44,"P":6,"UP":7},"m4_cycles":150},"at5000":[5000,28,28,true,null,1992,10]},"exch":{"case":"t3_dg_1d2d_k512","set":"trace-mem","before":38,"label":"SYNCS.EXCH.64@0x0260","kind":"value32u","form":"elect","tmpl":["CS2R.32 R0, SR_CLOCKLO","LEA.LO R0, PT, R0, 0x1, 0x7","ELECT P3, URZ, ~URZ","ULOP3.LUT UPT, UR0, UR62, 0x3f, URZ, 0xc0, !UPT","UIMAD.WIDE.U32 {UR0,UR1}, UPT, UR0, 0x10, {UR60,UR61}","@P3 STG.E [RZ+UR0+0x20], R0","MOV R0, UR8, 0xf","@P3 STG.E [RZ+UR0+0x28], R0","@P3 STG.E [RZ+UR0+0x2c], RZ","UIADD3 UR62, UPT, UPT, UR62, 0x1, URZ"],"values":[{"f":"R","n":1,"canon":0,"d":0,"uses":[1]},{"f":"R","n":1,"canon":0,"d":1,"uses":[5]},{"f":"P","n":1,"canon":3,"d":2,"uses":[5,7,8]},{"f":"UR","n":1,"canon":0,"d":3,"uses":[4]},{"f":"UR","n":2,"canon":0,"d":4,"uses":[5,7,8]},{"f":"R","n":1,"canon":0,"d":6,"uses":[7]}],"preds":[[],[0],[],[],[3],[1,2,4],[],[2,4,6],[2,4],[3]],"raw":[[1],[5],[5,7,8],[4],[5,7,8],[],[7],[],[],[]],"norders":14260,"vars":[{"part":[[0,1,5],[2],[3,4]],"body":["CS2R.32 R0, SR_CLOCKLO","LEA.LO R0, PT, R0, 0x1, 0x7","ELECT P3, URZ, ~URZ","ULOP3.LUT UPT, UR0, UR62, 0x3f, URZ, 0xc0, !UPT","UIMAD.WIDE.U32 {UR0,UR1}, UPT, UR0, 0x10, {UR60,UR61}","@P3 STG.E [RZ+UR0+0x20], R0","MOV R0, UR8, 0xf","@P3 STG.E [RZ+UR0+0x28], R0","@P3 STG.E [RZ+UR0+0x2c], RZ","UIADD3 UR62, UPT, UPT, UR62, 0x1, URZ"],"need":[0,1,0,0,8,22,0,84,20,8],"edges":[[0,1,4,"fix"],[0,5,4,"fix"],[0,6,1,"fix"],[0,7,4,"fix"],[1,5,4,"fix"],[1,6,1,"fix"],[1,7,4,"fix"],[2,5,13,"fix"],[2,7,13,"fix"],[2,8,13,"fix"],[3,4,4,"fix"],[3,5,12,"fix"],[3,7,12,"fix"],[3,8,12,"fix"],[3,9,1,"fix"],[4,5,8,"fix"],[4,7,8,"fix"],[4,8,8,"fix"],[5,6,1,"rd"],[6,0,1,"fix"],[6,1,6,"fix"],[6,5,4,"fix"],[6,7,4,"fix"],[7,0,1,"rd"],[7,1,1,"rd"]],"rel":[30,30,30,30,30,14,30,14,14,30],"claim":[0,0,0,0,0,1,0,1,0,0],"root":28,"greedy":[2,3,0,4,1,6,5,7,8,9],"n":1612,"cmin":46,"c":"FFFFFFFFFFFFGGGHFFFGFFFGGGGGGGGGGGGGHHHIGGGHGGGHKKKKKKKKKKKKLLLMKKKLLLLMHHHIKKKLEEEEEEEEEEEEFFFGEEEFEEEFBBBBBBBBBBBBCCCDBBBCBBBCBBBBBBBBBBBBCCCDBBBCGGGGHBBBCGBBBCBBBCGFFFFFFFFFFFFGGGHFFFGFFFGGGGGGGGGGGGGHHHIGGGHHHHIGGGHHHHICCCCCCCCCCCCDDDECCCDCCCDCCCCCCCCCCCCDDDECCCDHHHHICCCDHCCCDCCCDHHHHHHHHHHHHHIIIJHHHIIIIJGGGGGGGGGGGGHHHIGGGHLLLLMGGGHLIIIJHHHIMFFFGGGGHDDDEDDDEIHHHIGGGHLFFFFFFFFFFFFGGGHFFFGFFFGBBBBBBBBBBBBCCCDBBBCCCCDBBBBBBBBBBBBCCCDBBBCGGGGHBBBCGBBBCBBBCGCCCCCCCCCCCCDDDECCCDDDDEAAAAAAAAAAAABBBCAAABFFFFGAAABFCCCDAAABFBBBBBBBBBBBBBBBCBBBBFFFFGBBBBFEEEEEEEEEEEEEEEEEEEEFFFFGEEEEFJJJJJJJJJJKKCCCCFEEEEFJJEEEEEEEEEEEEEEEEEEEEFFFFGEEEEFEEEEFDDDEAAABFBBBBFEEEEFJJEEEEFFFFFFFFFFFFFFFFFFFFFGGGGHFFFFGFFFFGGGGGGGGGGGGGHHHIGGGHGGGHHHHHHHHHHHHHIIIJHHHIIIIJHHHIIIIJCCCCCCCCCCCCDDDECCCDCCCDCCCCCCCCCCCCDDDECCCDHHHHICCCDHCCCDCCCDHGGGGGGGGGGGGHHHIGGGHHHHIFFFFFFFFFFFFGGGHFFFGKKKKLFFFGKHHHIGGGHLGGGHHHHIDDDEDDDEIGGGHFFFGKCCCCCCCCCCCCDDDECCCDDDDEBBBBBBBBBBBBCCCDBBBCGGGGHBBBCGCCCDBBBCGBBBBBBBBBBBBCCCDBBBCGGGGHBBBCGFFFFFFFFFFFFFFFFFFFFGGGGHFFFFGKKKKKKKKKKLLBBBCGFFFFGKKFFFFFFFFFFFFFFFFFFFFGGGGHFFFFGFFFFGDDDEBBBCGBBBCGFFFFGKKFFFFGKKKKKKKKKKKKLLLMKKKLLLLMGGGGGGGGGGGGHHHIGGGHLLLLMGGGHLKKKLHHHIMFFFFFFFFFFFFGGGHFFFGKKKKLFFFGKJJJJJJJJJJJJJJJJJJJJKKKKLJJJJKOOOOOOOOOOPPFFFGKJJJJKOOKKKKKKKKKKKKKKKKKKKKLLLLMKKKKLLLLLMLLLMHHHIMGGGHLKKKKLPPLLLLMGGGGGGGGGGGGGGGGGGGGHHHHIGGGGHGGGGHJJJJJJJJJJJJJJJJJJJJKKKKLJJJJKKKKKLHHHHIJJJJKHHHIIIIJDDDEDDDEIHHHIFFFGKDDDECCCDHCCCDHGGGGHLLGGGGHKKKLGGGHLFFFGKJJJJKOOKKKKLHHHHIJJJJKFFFFFFFFFFFFFFFFFFFFGGGGHFFFFGFFFFGGGGGGGGGGGGGGGGGGGGGHHHHIGGGGHGGGGHKKKKKKKKKKKKKKKKKKKKLLLLMKKKKLLLLLMHHHHIKKKKL"},{"part":[[0],[1],[2],[3],[4],[5]],"body":["CS2R.32 R0, SR_CLOCKLO","LEA.LO R2, PT, R0, 0x1, 0x7","ELECT P3, URZ, ~URZ","ULOP3.LUT UPT, UR2, UR62, 0x3f, URZ, 0xc0, !UPT","UIMAD.WIDE.U32 {UR0,UR1}, UPT, UR2, 0x10, {UR60,UR61}","@P3 STG.E [RZ+UR0+0x20], R2","MOV R3, UR8, 0xf","@P3 STG.E [RZ+UR0+0x28], R3","@P3 STG.E [RZ+UR0+0x2c], RZ","UIADD3 UR62, UPT, UPT, UR62, 0x1, URZ"],"need":[0,1,0,0,8,22,0,84,20,8],"edges":[[0,1,4,"fix"],[1,5,4,"fix"],[2,5,13,"fix"],[2,7,13,"fix"],[2,8,13,"fix"],[3,4,4,"fix"],[3,9,1,"fix"],[4,5,8,"fix"],[4,7,8,"fix"],[4,8,8,"fix"],[6,7,4,"fix"]],"rel":[30,30,30,30,30,14,30,14,14,30],"claim":[0,0,0,0,0,1,0,1,0,0],"root":28,"greedy":[2,3,0,4,1,6,5,7,8,9],"n":14260,"cmin":29,"c":"JJJJJJKKLKKLFFGHGHFFGHGHGHGHHHFGFGGGKKLJJKLJKLKLJJKFGFGGGKJKFFGHGHFFGHGHGHGHHHFGFGGGFGFGGGJJKFGFGGGKJKFGFGGGGGHIHIGGHIHIHIHIIIGHGHHHGHGHHHKKKKKKLLMLLMGGHIHIGGHIHIHIHIIIGHGHHHLLMKKLMKLMLMKKLGHGHHHLKLGGHIHIGGHIHIHIHIIIGHGHHHGHGHHHKKLGHGHHHLKLGHGHHHOOOOOOPPQPPQKKLMLMKKLMLMLMLMMMKLKLLLPPQOOPQOPQPQOOPKLKLLLPOPLLMNMNLLMNMNMNMNNNLMLMMMMNMNNNPPQLMLMMMQPQMNMNNNHHIJIJHHIJIJIJIJJJHIHIIIHIHIIIKKLMLMKKLMLMLMLMMMKLKLLLLMLMMMIJIJJJKLKLLLLLMHIHIIIMLMHIHIIIOOPKLKLLLPOPLMLMMMIJIJJJKLKLLLHHIJIJHHIJIJIJIJJJHIHIIIHIHIIIIIJKJKIIJKJKJKJKKKIJIJJJIJIJJJMMNONOMMNONONONOOOMNMNNNNONOOOJKJKKKMNMNNNIIIIIIJJKJJKEEFGFGEEFGFGFGFGGGEFEFFFJJKIIJKIJKJKIIJEFEFFFJIJEEFGFGEEFGFGFGFGGGEFEFFFEFEFFFIIJEFEFFFJIJEFEFFFGGHIHIGGHIHIHIHIIIGHGHHHGHGHHHFFFFFFGGHGGHBBCDCDBBCDCDCDCDDDBCBCCCGGHFFGHFGHGHFFGBCBCCCGFGCCDEDECCDEDEDEDEEECDCDDDDEDEEEFFGBCBCCCGFGCDCDDDFFFFFFGGHGGHBBCDCDBBCDCDCDCDDDBCBCCCGGHFFGHFGHGHFFGBCBCCCGFGBBCDCDBBCDCDCDCDDDBCBCCCFFFFFFGGHGGHGHFFGFGGHHGHBCBCCCFFGGFGKKLHHIJHIKHIIJHHIHKKLIHKLIJJILFFGBCBCCCGFGBCBCCCFFGGFGKHIIHKBBCDCDBBCDCDCDCDDDBCBCCCCDCDDDBBCDCDBBCDCDCDCDDDBCBCCCFFFFFFGGHGGHGHFFGFGGHHGHBCBCCCFFGGFGBCBCCCBCBCCCFFGGFGFFGBCBCCCGFGCDCDDDFFGBCBCCCGFGBCBCCCFFGGFGKHIIHKCDCDDDBCBCCCFFGGFGEEFGFGEEFGFGFGFGGGEFEFFFEFEFFFCCDEDECCDEDEDEDEEECDCDDDCDCDDDCCDEDECCDEDEDEDEEECDCDDDGGGGGGHHIHHIHIGGHGHHIIHICDCDDDGGHHGHCDCDDDCDCDDDGGHHGHJJJJJJKKLKKLFFGHGHFFGHGHGHGHHHFGFGGGKKLJJKLJKLKLJJKFGFGGGKJKFFGHGHFFGHGHGHGHHHFGFGGGFGFGGGJJKFGFGGGKJKFGFGGGKKKKKKLLMLLMGGHIHIGGHIHIHIHIIIGHGHHHLLMKKLMKLMLMKKLGHGHHHLKLHHIJIJHHIJIJIJIJJJHIHIIIIJIJJJLLMHIHIIIMLMIJIJJJHHIJIJHHIJIJIJIJJJHIHIIIHIHIIIIIJKJKIIJKJKJKJKKKIJIJJJJKJKKKIJIJJJJKJKKKKKLGHGHHHLKLGHGHHHLLMHIHIIIMLMIJIJJJHIHIIIIJIJJJGGGGGGHHIHHICCDEDECCDEDEDEDEEECDCDDDHHIGGHIGHIHIGGHCDCDDDHGHCCDEDECCDEDEDEDEEECDCDDDDEDEEEGGHCDCDDDHGHCDCDDDGGGGGGHHIHHICCDEDECCDEDEDEDEEECDCDDDHHIGGHIGHIHIGGHCDCDDDHGHCCDEDECCDEDEDEDEEECDCDDDGGGGGGHHIHHIHIGGHGHHIIHICDCDDDGGHHGHLLMIIJKIJLIJJKIIJILLMJILMJKKJMGGHCDCDDDHGHCDCDDDGGHHGHLIJJILCCDEDECCDEDEDEDEEECDCDDDCDCDDDCCDEDECCDEDEDEDEEECDCDDDGGGGGGHHIHHIHIGGHGHHIIHICDCDDDGGHHGHCDCDDDCDCDDDGGHHGHGGHCDCDDDHGHCDCDDDGGHCDCDDDHGHCDCDDDGGHHGHLIJJILCDCDDDCDCDDDGGHHGHLLLLLLMMNMMNHHIJIJHHIJIJIJIJJJHIHIIIMMNLLMNLMNMNLLMHIHIIIMLMJJKLKLJJKLKLKLKLLLJKJKKKKLKLLLMMNIJIJJJNMNJKJKKKKKKKKKLLMLLMGGHIHIGGHIHIHIHIIIGHGHHHLLMKKLMKLMLMKKLGHGHHHLKLGGHIHIGGHIHIHIHIIIGHGHHHKKKKKKLLMLLMLMKKLKLLMMLMGHGHHHKKLLKLPPQMMNOMNPMNNOMMNMPPQNMPQNOONQKKLGHGHHHLKLGHGHHHKKLLKLPMNNMPJJKLKLJJKLKLKLKLLLJKJKKKKLKLLLHHIJIJHHIJIJIJIJJJHIHIIILLLLLLMMNMMNMNLLMLMMNNMNHIHIIILLMMLMJKJKKKIJIJJJMMNNMNMMNIJIJJJNMNKLKLLLLLMHIHIIIMLMHIHIIILLMMLMQNOONQKLKLLLIJIJJJMMNNMNFFGHGHFFGHGHGHGHHHFGFGGGFGFGGGGGHIHIGGHIHIHIHIIIGHGHHHHIHIIIGHGHHHHIHIIIDDEFEFDDEFEFEFEFFFDEDEEEDEDEEEDDEFEFDDEFEFEFEFFFDEDEEEHHHHHHIIJIIJIJHHIHIIJJIJDEDEEEHHIIHIDEDEEEDEDEEEHHIIHIHHIJIJHHIJIJIJIJJJHIHIIIIJIJJJGGHIHIGGHIHIHIHIIIGHGHHHKKKKKKLLMLLMLMKKLKLLMMLMGHGHHHKKLLKLIJIJJJHIHIIILLMMLMFGFGGGGHGHHHEFEFFFEFEFFFIIJJIJHIHIIIGHGHHHKKLLKLJJKFGFGGGKJKFGFGGGKKLGHGHHHLKLHIHIIIHIHIIIIJIJJJHHIDEDEEEIHIDEDEEEHHIDEDEEEIHIDEDEEEHHIIHIMJKKJMDEDEEEDEDEEEHHIIHILLMHIHIIIMLMJKJKKKKKLGHGHHHLKLGHGHHHKKLLKLPMNNMPJKJKKKHIHIIILLMMLMGHGHHHHIHIIIEFEFFFEFEFFFIIJJIJHIHIIIGHGHHHKKLLKLFFGHGHFFGHGHGHGHHHFGFGGGFGFGGGGGHIHIGGHIHIHIHIIIGHGHHHGHGHHHKKLMLMKKLMLMLMLMMMKLKLLLLMLMMMHIHIIIKLKLLLEEFGFGEEFGFGFGFGGGEFEFFFEFEFFFDDEFEFDDEFEFEFEFFFDEDEEEDEDEEEDDEFEFDDEFEFEFEFFFDEDEEEHHHHHHIIJIIJIJHHIHIIJJIJDEDEEEHHIIHIDEDEEEDEDEEEHHIIHIFFGHGHFFGHGHGHGHHHFGFGGGFGFGGGIIJKJKIIJKJKJKJKKKIJIJJJJKJKKKGHGHHHIJIJJJEEFGFGEEFGFGFGFGGGEFEFFFEFEFFFEEFGFGEEFGFGFGFGGGEFEFFFIIIIIIJJKJJKJKIIJIJJKKJKEFEFFFIIJJIJEFEFFFEFEFFFIIJJIJJJKLKLJJKLKLKLKLLLJKJKKKKLKLLLIIJKJKIIJKJKJKJKKKIJIJJJMMMMMMNNONNONOMMNMNNOONOIJIJJJMMNNMNKLKLLLJKJKKKNNOONOGHGHHHIJIJJJFGFGGGFGFGGGJJKKJKJKJKKKIJIJJJMMNNMNJJJJJJKKLKKLFFGHGHFFGHGHGHGHHHFGFGGGKKLJJKLJKLKLJJKFGFGGGKJKFFGHGHFFGHGHGHGHHHFGFGGGFGFGGGJJKFGFGGGKJKFGFGGGHHIJIJHHIJIJIJIJJJHIHIIIHIHIIIFFFFFFGGHGGHBBCDCDBBCDCDCDCDDDBCBCCCGGHFFGHFGHGHFFGBCBCCCGFGDDEFEFDDEFEFEFEFFFDEDEEEEFEFFFGGHCDCDDDHGHDEDEEEFFFFFFGGHGGHBBCDCDBBCDCDCDCDDDBCBCCCGGHFFGHFGHGHFFGBCBCCCGFGBBCDCDBBCDCDCDCDDDBCBCCCFFFFFFGGHGGHGHFFGFGGHHGHBCBCCCFFGGFGKKLHHIJHIKHIIJHHIHKKLIHKLIJJILFFGBCBCCCGFGBCBCCCFFGGFGKHIIHKBBCDCDBBCDCDCDCDDDBCBCCCCDCDDDBBCDCDBBCDCDCDCDDDBCBCCCFFFFFFGGHGGHGHFFGFGGHHGHBCBCCCFFGGFGBCBCCCBCBCCCFFGGFGFFGBCBCCCGFGDEDEEEFFGBCBCCCGFGBCBCCCFFGGFGKHIIHKCDCDDDBCBCCCFFGGFGFFGHGHFFGHGHGHGHHHFGFGGGFGFGGGDDEFEFDDEFEFEFEFFFDEDEEEDEDEEEDDEFEFDDEFEFEFEFFFDEDEEEHHHHHHIIJIIJIJHHIHIIJJIJDEDEEEHHIIHIDEDEEEDEDEEEHHIIHIGGGGGGHHIHHICCDEDECCDEDEDEDEEECDCDDDHHIGGHIGHIHIGGHCDCDDDHGHEEFGFGEEFGFGFGFGGGEFEFFFFGFGGGHHIDEDEEEIHIEFEFFFEEEEEEFFGFFGAABCBCAABCBCBCBCCCABABBBFFGEEFGEFGFGEEFABABBBFEFAABCBCAABCBCBCBCCCABABBBEEEEEEFFGFFGFGEEFEFFGGFGABABBBEEFFEFJJKGGHIGHJGHHIGGHGJJKHGJKHIIHKEEFABABBBFEFABABBBEEFFEFJGHHGJCCDEDECCDEDEDEDEEECDCDDDDEDEEEAABCBCAABCBCBCBCCCABABBBEEEEEEFFGFFGFGEEFEFFGGFGABABBBEEFFEFCDCDDDBCBCCCFFGGFGGGHCDCDDDHGHEFEFFFEEFABABBBFEFABABBBEEFFEFJGHHGJCDCDDDABABBBEEFFEFFFFFFFGGHGGHCCCDCDDDEFEFCCDECDCCDECDFFGEEFGEFGFGFFGCCDECDFEFBBCDCDAABCBCBCBCCCBCABBBEEEEEEFFGFFGFGEEFEFFGGFGBCABBBEEFFEFJJKGGHIGHJGHHIGGHGJJKHGJKHIIHKFFGCCDECDFEFBCABBBEEFFEFJGHHGJDDEFEFCCCCCCDECCDCDECCDCEEEEEEFFGFFGFGEEFEFFGGFGDECCDCEEFFEFIIIIIIIIIIIIJJJKJJJKJKIIJIIIIJIIJJJKKJJKDECCDCEEFFEFIIIJJIIJNNOKKLMKLNKLJKIIJILLMJILNKLJILLMKKLKKKKLKKNNNOLKKNOLMKJMMLLOGGHDDEFDEGEFCDBBCBEEFFEFJGHHGJEFDDEDEEFFEFIIIJJIIJNKLJILLKKNEEFGFGEEFGFGFGFGGGEFEFFFFGFGGGAABCBCAABCBCBCBCCCABABBBEEEEEEFFGFFGFGEEFEFFGGFGABABBBEEFFEFEFEFFFBCBCCCFFGGFGBBCDCDAABCBCBCBCCCBCABBBEEEEEEFFGFFGFGEEFEFFGGFGBCABBBEEFFEFIIIIIIIIIIIIJJJKJJJKJKIIJIIIIJIIJJJKKJJKCDBBCBEEFFEFIIIJJIIJEFEFFFABABBBEEFFEFBCABBBEEFFEFIIIJJIIJHHIDEDEEEIHIFGFGGGEEFABABBBFEFABABBBEEFFEFJGHHGJDEDEEEBCBCCCFFGGFGFFGCCDECDFEFBCABBBEEFFEFJGHHGJDECCDCEEFFEFIIIJJIIJNKLJILLKKNFGFGGGBCBCCCFFGGFGBCABBBEEFFEFIIIJJIIJHHIJIJHHIJIJIJIJJJHIHIIIHIHIIIDDEFEFDDEFEFEFEFFFDEDEEEEFEFFFDDEFEFDDEFEFEFEFFFDEDEEEHHHHHHIIJIIJIJHHIHIIJJIJDEDEEEHHIIHIDEDEEEDEDEEEHHIIHIDDEFEFDDEFEFEFEFFFDEDEEEEFEFFFBBCDCDBBCDCDCDCDDDBCBCCCFFFFFFGGHGGHGHFFGFGGHHGHBCBCCCFFGGFGDEDEEEBCBCCCFFGGFGCCDEDEBBCDCDCDCDDDCDBCCCFFFFFFGGHGGHGHFFGFGGHHGHCDBCCCFFGGFGJJJJJJJJJJJJKKKLKKKLKLJJKJJJJKJJKKKLLKKLDECCDCFFGGFGJJJKKJJKEFEFFFBCBCCCFFGGFGCDBCCCFFGGFGJJJKKJJKKKKKKKLLMLLMGGHIHIGGHIHIHIHIIIGHGHHHLLMKKLMKLMLMKKLGHGHHHLKLGGHIHIGGHIHIHIHIIIGHGHHHGHGHHHKKLGHGHHHLKLGHGHHHLLLLLLMMNMMNHHIJIJHHIJIJIJIJJJHIHIIIMMNLLMNLMNMNLLMHIHIIIMLMIIJKJKIIJKJKJKJKKKIJIJJJJKJKKKMMNIJIJJJNMNJKJKKKIIJKJKIIJKJKJKJKKKIJIJJJIJIJJJJJKLKLJJKLKLKLKLLLJKJKKKKLKLLLJKJKKKKLKLLLLLMHIHIIIMLMHIHIIIMMNIJIJJJNMNJKJKKKIJIJJJJKJKKKGGGGGGHHIHHICCDEDECCDEDEDEDEEECDCDDDHHIGGHIGHIHIGGHCDCDDDHGHDDEFEFDDEFEFEFEFFFDEDEEEEFEFFFGGHCDCDDDHGHDEDEEEGGGGGGHHIHHICCDEDECCDEDEDEDEEECDCDDDHHIGGHIGHIHIGGHCDCDDDHGHCCDEDECCDEDEDEDEEECDCDDDGGGGGGHHIHHIHIGGHGHHIIHICDCDDDGGHHGHLLMIIJKIJLIJJKIIJILLMJILMJKKJMGGHCDCDDDHGHCDCDDDGGHHGHLIJJILCCDEDECCDEDEDEDEEECDCDDDCDCDDDCCDEDECCDEDEDEDEEECDCDDDGGGGGGHHIHHIHIGGHGHHIIHICDCDDDGGHHGHCDCDDDCDCDDDGGHHGHGGHCDCDDDHGHDEDEEEGGHCDCDDDHGHCDCDDDGGHHGHLIJJILCDCDDDCDCDDDGGHHGHKKKKKKLLMLLMGGHIHIGGHIHIHIHIIIGHGHHHLLMKKLMKLMLMKKLGHGHHHLKLIIJKJKIIJKJKJKJKKKIJIJJJJKJKKKLLMHIHIIIMLMIJIJJJJJJJJJKKLKKLFFGHGHFFGHGHGHGHHHFGFGGGKKLJJKLJKLKLJJKFGFGGGKJKFFGHGHFFGHGHGHGHHHFGFGGGJJJJJJKKLKKLKLJJKJKKLLKLFGFGGGJJKKJKOOPLLMNLMOLMMNLLMLOOPMLOPMNNMPJJKFGFGGGKJKFGFGGGJJKKJKOLMMLOIIJKJKIIJKJKJKJKKKIJIJJJJKJKKKGGHIHIGGHIHIHIHIIIGHGHHHKKKKKKLLMLLMLMKKLKLLMMLMGHGHHHKKLLKLIJIJJJHIHIIILLMMLMLLMHIHIIIMLMJKJKKKKKLGHGHHHLKLGHGHHHKKLLKLPMNNMPJKJKKKHIHIIILLMMLMGGHIHIGGHIHIHIHIIIGHGHHHGHGHHHHHIJIJHHIJIJIJIJJJHIHIIIIJIJJJHIHIIIIJIJJJEEFGFGEEFGFGFGFGGGEFEFFFEFEFFFEEFGFGEEFGFGFGFGGGEFEFFFIIIIIIJJKJJKJKIIJIJJKKJKEFEFFFIIJJIJEFEFFFEFEFFFIIJJIJGGHIHIGGHIHIHIHIIIGHGHHHHIHIIIFFGHGHFFGHGHGHGHHHFGFGGGJJJJJJKKLKKLKLJJKJKKLLKLFGFGGGJJKKJKHIHIIIGHGHHHKKLLKLGHGHHHHIHIIIFGFGGGFGFGGGJJKKJKHIHIIIGHGHHHKKLLKLKKLGHGHHHLKLGHGHHHLLMHIHIIIMLMIJIJJJIJIJJJJKJKKKHHIDEDEEEIHIDEDEEEHHIDEDEEEIHIDEDEEEHHIIHIMJKKJMDEDEEEDEDEEEHHIIHIKKLGHGHHHLKLIJIJJJJJKFGFGGGKJKFGFGGGJJKKJKOLMMLOIJIJJJGHGHHHKKLLKLGHGHHHHIHIIIEFEFFFEFEFFFIIJJIJGHGHHHFGFGGGJJKKJKGGGGGGHHIHHICCDEDECCDEDEDEDEEECDCDDDHHIGGHIGHIHIGGHCDCDDDHGHEEFGFGEEFGFGFGFGGGEFEFFFFGFGGGHHIDEDEEEIHIEFEFFFFFFFFFGGHGGHBBCDCDBBCDCDCDCDDDBCBCCCGGHFFGHFGHGHFFGBCBCCCGFGBBCDCDBBCDCDCDCDDDBCBCCCFFFFFFGGHGGHGHFFGFGGHHGHBCBCCCFFGGFGKKLHHIJHIKHIIJHHIHKKLIHKLIJJILFFGBCBCCCGFGBCBCCCFFGGFGKHIIHKCCDEDECCDEDEDEDEEECDCDDDDEDEEEBBCDCDBBCDCDCDCDDDBCBCCCFFFFFFGGHGGHGHFFGFGGHHGHBCBCCCFFGGFGCDCDDDBCBCCCFFGGFGGGHCDCDDDHGHEFEFFFFFGBCBCCCGFGBCBCCCFFGGFGKHIIHKCDCDDDBCBCCCFFGGFGFFFFFFGGHGGHBBCDCDCCDEDECDCDDDBCCDCCGGHFFGHFGHGHFFGBCCDCCGFGBBCDCDBBCDCDCDCDDDBCBCCCFFFFFFGGHGGHGHFFGFGGHHGHBCBCCCFFGGFGKKLHHIJHIKHIIJHHIHKKLIHKLIJJILFFGBCCDCCGFGBCBCCCFFGGFGKHIIHKCCDEDEBBCDCDCDCDDDCDBCCCFFFFFFGGHGGHGHFFGFGGHHGHCDBCCCFFGGFGJJJJJJJJJJJJKKKLKKKLKLJJKJJJJKJJKKKLLKKLCDBCCCFFGGFGJJJKKJJKOOPLLMNLMOLMKLJJKJMMNKJMOLMKJMMNLLMLLLLMLLOOOPMLLOPMNLKNNMMPFFGCCDECDGFGBCBCCCFFGGFGKHIIHKDECCDCFFGGFGJJJKKJJKOLMKJMMLLOEEFGFGEEFGFGFGFGGGEFEFFFFGFGGGBBCDCDBBCDCDCDCDDDBCBCCCFFFFFFGGHGGHGHFFGFGGHHGHBCBCCCFFGGFGEFEFFFBCBCCCFFGGFGBBCDCDBBCDCDCDCDDDBCBCCCFFFFFFGGHGGHGHFFGFGGHHGHBCBCCCFFGGFGJJJJJJJJJJJJKKKLKKKLKLJJKJJJJKJJKKKLLKKLBCBCCCFFGGFGJJJKKJJKEFEFFFBCBCCCFFGGFGBCBCCCFFGGFGJJJKKJJKHHIDEDEEEIHIFGFGGGFFGBCBCCCGFGBCBCCCFFGGFGKHIIHKDEDEEEBCBCCCFFGGFGFFGBCCDCCGFGBCBCCCFFGGFGKHIIHKCDBCCCFFGGFGJJJKKJJKOLMKJMMLLOFGFGGGBCBCCCFFGGFGBCBCCCFFGGFGJJJKKJJKOOOOOOPPQPPQKKLMLMKKLMLMLMLMMMKLKLLLPPQOOPQOPQPQOOPKLKLLLPOPMMNONOMMNONONONOOOMNMNNNNONOOOPPQLMLMMMQPQMNMNNNKKKKKKLLMLLMGGHIHIGGHIHIHIHIIIGHGHHHLLMKKLMKLMLMKKLGHGHHHLKLGGHIHIGGHIHIHIHIIIGHGHHHKKKKKKLLMLLMLMKKLKLLMMLMGHGHHHKKLLKLPPQMMNOMNPMNNOMMNMPPQNMPQNOONQKKLGHGHHHLKLGHGHHHKKLLKLPMNNMPKKLMLMKKLMLMLMLMMMKLKLLLLMLMMMIIJKJKIIJKJKJKJKKKIJIJJJMMMMMMNNONNONOMMNMNNOONOIJIJJJMMNNMNKLKLLLJKJKKKNNOONOOOPKLKLLLPOPMNMNNNLLMHIHIIIMLMHIHIIILLMMLMQNOONQKLKLLLIJIJJJMMNNMNJJJJJJKKLKKLFFGHGHFFGHGHGHGHHHFGFGGGKKLJJKLJKLKLJJKFGFGGGKJKFFGHGHFFGHGHGHGHHHFGFGGGJJJJJJKKLKKLKLJJKJKKLLKLFGFGGGJJKKJKOOPLLMNLMOLMMNLLMLOOPMLOPMNNMPJJKFGFGGGKJKFGFGGGJJKKJKOLMMLOFFGHGHFFGHGHGHGHHHFGFGGGJJJJJJKKLKKLKLJJKJKKLLKLFGFGGGJJKKJKNNNNNNNNNNNNOOOPOOOPOPNNONNNNONNOOOPPOOPFGFGGGJJKKJKNNNOONNOSSTPPQRPQSPQOPNNONQQRONQSPQONQQRPPQPPPPQPPSSSTQPPSTQRPORRQQTJJKFGFGGGKJKFGFGGGJJKKJKOLMMLOFGFGGGJJKKJKNNNOONNOSPQONQQPPSMMNONOMMNONONONOOOMNMNNNNONOOOIIJKJKIIJKJKJKJKKKIJIJJJMMMMMMNNONNONOMMNMNNOONOIJIJJJMMNNMNMNMNNNJKJKKKNNOONOGGHIHIGGHIHIHIHIIIGHGHHHKKKKKKLLMLLMLMKKLKLLMMLMGHGHHHKKLLKLOOOOOOOOOOOOPPPQPPPQPQOOPOOOOPOOPPPQQPPQGHGHHHKKLLKLOOOPPOOPMNMNNNIJIJJJMMNNMNHIHIIILLMMLMPPPQQPPQPPQLMLMMMQPQNONOOOLLMHIHIIIMLMHIHIIILLMMLMQNOONQLMLMMMJKJKKKNNOONOKKLGHGHHHLKLGHGHHHKKLLKLPMNNMPGHGHHHKKLLKLOOOPPOOPTQRPORRQQTNONOOOJKJKKKNNOONOHIHIIILLMMLMPPPQQPPQIIJKJKIIJKJKJKJKKKIJIJJJIJIJJJJJKLKLJJKLKLKLKLLLJKJKKKKLKLLLJKJKKKKLKLLLEEFGFGEEFGFGFGFGGGEFEFFFEFEFFFEEFGFGEEFGFGFGFGGGEFEFFFIIIIIIJJKJJKJKIIJIJJKKJKEFEFFFIIJJIJEFEFFFEFEFFFIIJJIJIIJKJKIIJKJKJKJKKKIJIJJJJKJKKKFFGHGHFFGHGHGHGHHHFGFGGGJJJJJJKKLKKLKLJJKJKKLLKLFGFGGGJJKKJKIJIJJJGHGHHHKKLLKLIJIJJJJKJKKKFGFGGGFGFGGGJJKKJKIJIJJJGHGHHHKKLLKLDDEFEFDDEFEFEFEFFFDEDEEEEFEFFFCCDEDECCDEDEDEDEEECDCDDDGGGGGGHHIHHIHIGGHGHHIIHICDCDDDGGHHGHDEDEEECDCDDDGGHHGHCCDEDECCDEDEDEDEEECDCDDDGGGGGGHHIHHIHIGGHGHHIIHICDCDDDGGHHGHKKKKKKKKKKKKLLLMLLLMLMKKLKKKKLKKLLLMMLLMCDCDDDGGHHGHKKKLLKKLEFEFFFCDCDDDGGHHGHCDCDDDGGHHGHKKKLLKKLKKLMLMKKLMLMLMLMMMKLKLLLLMLMMMGGHIHIGGHIHIHIHIIIGHGHHHKKKKKKLLMLLMLMKKLKLLMMLMGHGHHHKKLLKLKLKLLLHIHIIILLMMLMFFGHGHFFGHGHGHGHHHFGFGGGJJJJJJKKLKKLKLJJKJKKLLKLFGFGGGJJKKJKNNNNNNNNNNNNOOOPOOOPOPNNONNNNONNOOOPPOOPFGFGGGJJKKJKNNNOONNOLMLMMMHIHIIILLMMLMGHGHHHKKLLKLOOOPPOOPIJIJJJJKJKKKEFEFFFEFEFFFIIJJIJIJIJJJFGFGGGJJKKJKEFEFFFDEDEEEHHIIHIDEDEEEHHIIHILLLMMLLMKLKLLLGHGHHHKKLLKLFGFGGGJJKKJKNNNOONNOLLMHIHIIIMLMHIHIIIMMNIJIJJJNMNJKJKKKJKJKKKKLKLLLHHIDEDEEEIHIEFEFFFHHIDEDEEEIHIDEDEEEHHIIHIMJKKJMDEDEEEDEDEEEHHIIHILLMHIHIIIMLMJKJKKKJJKFGFGGGKJKFGFGGGJJKKJKOLMMLOIJIJJJGHGHHHKKLLKLHIHIIIIJIJJJFGFGGGFGFGGGJJKKJKHIHIIIGHGHHHKKLLKLHHIDEDEEEIHIFGFGGGGGHCDCDDDHGHCDCDDDGGHHGHLIJJILDEDEEECDCDDDGGHHGHGGHCDCDDDHGHCDCDDDGGHHGHLIJJILCDCDDDGGHHGHKKKLLKKLPMNLKNNMMPFGFGGGCDCDDDGGHHGHCDCDDDGGHHGHKKKLLKKLOOPKLKLLLPOPMNMNNNKKLGHGHHHLKLGHGHHHKKLLKLPMNNMPKLKLLLIJIJJJMMNNMNJJKFGFGGGKJKFGFGGGJJKKJKOLMMLOFGFGGGJJKKJKNNNOONNOSPQONQQPPSMNMNNNIJIJJJMMNNMNGHGHHHKKLLKLOOOPPOOPJKJKKKKLKLLLFGFGGGFGFGGGJJKKJKJKJKKKGHGHHHKKLLKLEFEFFFDEDEEEHHIIHIDEDEEEHHIIHILLLMMLLMKLKLLLGHGHHHKKLLKLFGFGGGJJKKJKNNNOONNOHHIJIJHHIJIJIJIJJJHIHIIIHIHIIIIIJKJKIIJKJKJKJKKKIJIJJJIJIJJJMMNONOMMNONONONOOOMNMNNNNONOOOJKJKKKMNMNNNGGHIHIGGHIHIHIHIIIGHGHHHGHGHHHDDEFEFDDEFEFEFEFFFDEDEEEDEDEEEDDEFEFDDEFEFEFEFFFDEDEEEHHHHHHIIJIIJIJHHIHIIJJIJDEDEEEHHIIHIDEDEEEDEDEEEHHIIHIHHIJIJHHIJIJIJIJJJHIHIIIHIHIIIIIJKJKIIJKJKJKJKKKIJIJJJJKJKKKIJIJJJJKJKKKEEFGFGEEFGFGFGFGGGEFEFFFEFEFFFEEFGFGEEFGFGFGFGGGEFEFFFIIIIIIJJKJJKJKIIJIJJKKJKEFEFFFIIJJIJEFEFFFEFEFFFIIJJIJJJKLKLJJKLKLKLKLLLJKJKKKKLKLLLIIJKJKIIJKJKJKJKKKIJIJJJMMMMMMNNONNONOMMNMNNOONOIJIJJJMMNNMNKLKLLLJKJKKKNNOONOHIHIIIIJIJJJFGFGGGFGFGGGJJKKJKJKJKKKIJIJJJMMNNMNGGHIHIGGHIHIHIHIIIGHGHHHGHGHHHCCDEDECCDEDEDEDEEECDCDDDDEDEEECCDEDECCDEDEDEDEEECDCDDDGGGGGGHHIHHIHIGGHGHHIIHICDCDDDGGHHGHCDCDDDCDCDDDGGHHGHDDEFEFDDEFEFEFEFFFDEDEEEEFEFFFBBCDCDBBCDCDCDCDDDBCBCCCFFFFFFGGHGGHGHFFGFGGHHGHBCBCCCFFGGFGDEDEEEBCBCCCFFGGFGCCDEDEBBCDCDCDCDDDCDBCCCFFFFFFGGHGGHGHFFGFGGHHGHCDBCCCFFGGFGJJJJJJJJJJJJKKKLKKKLKLJJKJJJJKJJKKKLLKKLDECCDCFFGGFGJJJKKJJKEFEFFFBCBCCCFFGGFGCDBCCCFFGGFGJJJKKJJKHHIJIJHHIJIJIJIJJJHIHIIIHIHIIIIIJKJKIIJKJKJKJKKKIJIJJJJKJKKKIJIJJJJKJKKKDDEFEFDDEFEFEFEFFFDEDEEEDEDEEEDDEFEFDDEFEFEFEFFFDEDEEEHHHHHHIIJIIJIJHHIHIIJJIJDEDEEEHHIIHIDEDEEEDEDEEEHHIIHIHHIJIJHHIJIJIJIJJJHIHIIIIJIJJJGGHIHIGGHIHIHIHIIIGHGHHHKKKKKKLLMLLMLMKKLKLLMMLMGHGHHHKKLLKLIJIJJJHIHIIILLMMLMHIHIIIIJIJJJEFEFFFEFEFFFIIJJIJHIHIIIGHGHHHKKLLKLDDEFEFDDEFEFEFEFFFDEDEEEEFEFFFCCDEDECCDEDEDEDEEECDCDDDGGGGGGHHIHHIHIGGHGHHIIHICDCDDDGGHHGHDEDEEECDCDDDGGHHGHCCDEDECCDEDEDEDEEECDCDDDGGGGGGHHIHHIHIGGHGHHIIHICDCDDDGGHHGHKKKKKKKKKKKKLLLMLLLMLMKKLKKKKLKKLLLMMLLMCDCDDDGGHHGHKKKLLKKLEFEFFFCDCDDDGGHHGHCDCDDDGGHHGHKKKLLKKLLLMNMNLLMNMNMNMNNNLMLMMMMNMNNNHHIJIJHHIJIJIJIJJJHIHIIILLLLLLMMNMMNMNLLMLMMNNMNHIHIIILLMMLMLMLMMMIJIJJJMMNNMNGGHIHIGGHIHIHIHIIIGHGHHHKKKKKKLLMLLMLMKKLKLLMMLMGHGHHHKKLLKLOOOOOOOOOOOOPPPQPPPQPQOOPOOOOPOOPPPQQPPQGHGHHHKKLLKLOOOPPOOPMNMNNNIJIJJJMMNNMNHIHIIILLMMLMPPPQQPPQIJIJJJJKJKKKEFEFFFEFEFFFIIJJIJIJIJJJGHGHHHKKLLKLEFEFFFDEDEEEHHIIHIDEDEEEHHIIHILLLMMLLMLMLMMMHIHIIILLMMLMGHGHHHKKLLKLOOOPPOOP"}],"named":{"exact":{"v":0,"order":[2,3,0,9,4,1,5,6,8,7],"cost":46},"greedy":{"v":1,"order":[2,3,0,4,1,6,5,7,8,9],"cost":29},"best":{"v":1,"order":[2,3,0,4,1,6,5,7,8,9],"cost":29}},"events":[["start","greedy",0,4650,null,null,null,null,null,7730],["node","greedy",0,4680,[],null,null,null,null,null],["node","greedy",0,4710,[2],null,null,null,null,null],["node","greedy",0,4740,[2,3],null,null,null,null,null],["node","greedy",0,4770,[2,3,0],null,null,null,null,null],["node","greedy",0,4800,[2,3,0,4],null,null,null,null,null],["node","greedy",0,4830,[2,3,0,4,1],null,null,null,null,null],["end","greedy",0,4830,null,null,null,null,null,null],["start","greedy",1,4830,null,null,null,null,null,7730],["node","greedy",1,4860,[],null,null,null,null,null],["node","greedy",1,4890,[2],null,null,null,null,null],["node","greedy",1,4920,[2,3],null,null,null,null,null],["node","greedy",1,4950,[2,3,0],null,null,null,null,null],["node","greedy",1,4980,[2,3,0,4],null,null,null,null,null],["node","greedy",1,5010,[2,3,0,4,1],null,null,null,null,null],["node","greedy",1,5040,[2,3,0,4,1,6],null,null,null,null,null],["node","greedy",1,5070,[2,3,0,4,1,6,5],null,null,null,null,null],["node","greedy",1,5100,[2,3,0,4,1,6,5,7],null,null,null,null,null],["node","greedy",1,5130,[2,3,0,4,1,6,5,7,8],null,null,null,null,null],["leaf","greedy",1,5260,[2,3,0,4,1,6,5,7,8,9],null,null,29,true,null],["end","greedy",1,5260,null,null,29,null,null,null],["start","optimal",1,5490,null,null,29,null,null,7730],["node","optimal",1,5520,[],null,29,null,null,null],["node","optimal",1,5550,[2],28,29,null,null,null],["node","optimal",1,5580,[2,3],28,29,null,null,null],["node","optimal",1,5610,[2,3,0],28,29,null,null,null],["node","optimal",1,5640,[2,3,0,9],28,29,null,null,null],["node","optimal",1,5670,[2,3,0,9,6],28,29,null,null,null],["node","optimal",1,5700,[2,3,0,9,6,4],28,29,null,null,null],["node","optimal",1,5730,[2,3,0,9,6,4,1],28,29,null,null,null],["prune","optimal",1,5760,[2,3,0,9,6,4,1,5],29,29,null,null,null],["prune","optimal",1,5790,[2,3,0,9,6,4,1,7],29,29,null,null,null],["prune","optimal",1,5820,[2,3,0,9,6,4,1,8],30,29,null,null,null],["prune","optimal",1,5850,[2,3,0,9,6,4,7],33,29,null,null,null],["prune","optimal",1,5880,[2,3,0,9,6,4,8],33,29,null,null,null],["prune","optimal",1,5910,[2,3,0,9,6,1],30,29,null,null,null],["node","optimal",1,5940,[2,3,0,9,4],28,29,null,null,null],["node","optimal",1,5970,[2,3,0,9,4,1],28,29,null,null,null],["node","optimal",1,6000,[2,3,0,9,4,1,6],28,29,null,null,null],["prune","optimal",1,6030,[2,3,0,9,4,1,6,5],29,29,null,null,null],["prune","optimal",1,6060,[2,3,0,9,4,1,6,7],29,29,null,null,null],["prune","optimal",1,6090,[2,3,0,9,4,1,6,8],30,29,null,null,null],["prune","optimal",1,6120,[2,3,0,9,4,1,5],33,29,null,null,null],["prune","optimal",1,6150,[2,3,0,9,4,1,8],33,29,null,null,null],["node","optimal",1,6180,[2,3,0,9,4,6],28,29,null,null,null],["node","optimal",1,6210,[2,3,0,9,4,6,1],28,29,null,null,null],["prune","optimal",1,6240,[2,3,0,9,4,6,1,5],29,29,null,null,null],["prune","optimal",1,6270,[2,3,0,9,4,6,1,7],29,29,null,null,null],["prune","optimal",1,6300,[2,3,0,9,4,6,1,8],30,29,null,null,null],["prune","optimal",1,6330,[2,3,0,9,4,6,7],33,29,null,null,null],["prune","optimal",1,6360,[2,3,0,9,4,6,8],33,29,null,null,null],["prune","optimal",1,6390,[2,3,0,9,4,8],34,29,null,null,null],["prune","optimal",1,6420,[2,3,0,9,1],30,29,null,null,null],["node","optimal",1,6450,[2,3,0,6],28,29,null,null,null],["node","optimal",1,6480,[2,3,0,6,4],28,29,null,null,null],["node","optimal",1,6510,[2,3,0,6,4,1],28,29,null,null,null],["node","optimal",1,6540,[2,3,0,6,4,1,9],28,29,null,null,null],["prune","optimal",1,6570,[2,3,0,6,4,1,9,5],29,29,null,null,null],["prune","optimal",1,6600,[2,3,0,6,4,1,9,7],29,29,null,null,null],["prune","optimal",1,6630,[2,3,0,6,4,1,9,8],30,29,null,null,null],["prune","optimal",1,6660,[2,3,0,6,4,1,5],29,29,null,null,null],["prune","optimal",1,6690,[2,3,0,6,4,1,7],29,29,null,null,null],["prune","optimal",1,6720,[2,3,0,6,4,1,8],30,29,null,null,null],["node","optimal",1,6750,[2,3,0,6,4,9],28,29,null,null,null],["node","optimal",1,6780,[2,3,0,6,4,9,1],28,29,null,null,null],["prune","optimal",1,6810,[2,3,0,6,4,9,1,5],29,29,null,null,null],["prune","optimal",1,6840,[2,3,0,6,4,9,1,7],29,29,null,null,null],["prune","optimal",1,6870,[2,3,0,6,4,9,1,8],30,29,null,null,null],["prune","optimal",1,6900,[2,3,0,6,4,9,7],33,29,null,null,null],["prune","optimal",1,6930,[2,3,0,6,4,9,8],33,29,null,null,null],["prune","optimal",1,6960,[2,3,0,6,4,7],33,29,null,null,null],["prune","optimal",1,6990,[2,3,0,6,4,8],33,29,null,null,null],["prune","optimal",1,7020,[2,3,0,6,9],29,29,null,null,null],["prune","optimal",1,7050,[2,3,0,6,1],30,29,null,null,null],["node","optimal",1,7080,[2,3,0,4],28,29,null,null,null],["node","optimal",1,7110,[2,3,0,4,1],28,29,null,null,null],["node","optimal",1,7140,[2,3,0,4,1,9],28,29,null,null,null],["dom","optimal",1,7170,[2,3,0,4,1,9,6],null,null,null,null,null],["prune","optimal",1,7200,[2,3,0,4,1,9,5],33,29,null,null,null],["prune","optimal",1,7230,[2,3,0,4,1,9,8],33,29,null,null,null],["node","optimal",1,7260,[2,3,0,4,1,6],28,29,null,null,null],["node","optimal",1,7290,[2,3,0,4,1,6,9],28,29,null,null,null],["prune","optimal",1,7320,[2,3,0,4,1,6,9,5],29,29,null,null,null],["prune","optimal",1,7350,[2,3,0,4,1,6,9,7],29,29,null,null,null],["prune","optimal",1,7380,[2,3,0,4,1,6,9,8],30,29,null,null,null],["prune","optimal",1,7410,[2,3,0,4,1,6,5],29,29,null,null,null],["prune","optimal",1,7440,[2,3,0,4,1,6,7],29,29,null,null,null],["prune","optimal",1,7470,[2,3,0,4,1,6,8],30,29,null,null,null],["prune","optimal",1,7500,[2,3,0,4,1,5],33,29,null,null,null],["prune","optimal",1,7530,[2,3,0,4,1,8],33,29,null,null,null],["node","optimal",1,7560,[2,3,0,4,6],28,29,null,null,null],["node","optimal",1,7590,[2,3,0,4,6,9],28,29,null,null,null],["dom","optimal",1,7620,[2,3,0,4,6,9,1],null,null,null,null,null],["prune","optimal",1,7650,[2,3,0,4,6,9,7],33,29,null,null,null],["prune","optimal",1,7680,[2,3,0,4,6,9,8],33,29,null,null,null],["node","optimal",1,7710,[2,3,0,4,6,1],28,29,null,null,null],["node","optimal",1,7740,[2,3,0,4,6,1,9],28,29,null,null,null],["budget","optimal",1,7740,[2,3,0,4,6,1,9],null,null,null,null,null],["budget","optimal",1,7740,[2,3,0,4,6,1],null,null,null,null,null],["budget","optimal",1,7740,[2,3,0,4,6],null,null,null,null,null],["budget","optimal",1,7740,[2,3,0,4],null,null,null,null,null],["budget","optimal",1,7740,[2,3,0],null,null,null,null,null],["budget","optimal",1,7740,[2,3],null,null,null,null,null],["budget","optimal",1,7740,[2],null,null,null,null,null],["budget","optimal",1,7740,[],null,null,null,null,null],["end","optimal",1,7740,null,null,29,null,null,null]],"w0":2730,"rep":{"search_ms":5.059,"dfs_nodes":92,"pruned":45,"proven":false,"capped_in":"optimal","work":5010,"free_sb":[0,2,3,4,5],"kernel_busy_sb":[1],"free":{"R":160,"UR":55,"P":4,"UP":7},"m4_cycles":195},"at5000":[5000,29,29,false,"optimal",5010,92]},"smax":{"case":"t1_softmax","set":"trace-mem","before":42,"label":"LDGSTS.E.BYPASS.128@0x02a0","kind":"value64","form":"psave:P1","tmpl":["SEL R14, RZ, 0x1, !P1","CS2R.32 R11, SR_CLOCKLO","LEA.LO R11, PT, R11, 0x1, 0x6","ELECT P1, URZ, ~URZ","ULOP3.LUT UPT, UR0, UR62, 0x3f, URZ, 0xc0, !UPT","UIMAD.WIDE.U32 {UR0,UR1}, UPT, UR0, 0x10, {UR60,UR61}","@P1 STG.E [RZ+UR0+0x20], R11","@P1 STG.E.64 [RZ+UR0+0x28], {R12,R13}","ISETP.NE.AND P1, PT, R14, RZ, PT","UIADD3 UR62, UPT, UPT, UR62, 0x1, URZ"],"values":[{"f":"R","n":1,"canon":14,"d":0,"uses":[8]},{"f":"R","n":1,"canon":11,"d":1,"uses":[2]},{"f":"R","n":1,"canon":11,"d":2,"uses":[6]},{"f":"UR","n":1,"canon":0,"d":4,"uses":[5]},{"f":"UR","n":2,"canon":0,"d":5,"uses":[6,7]}],"preds":[[],[],[1],[0],[],[4],[2,3,5],[3,5],[0,3,6,7],[4]],"raw":[[8],[2],[6],[],[5],[6,7],[],[],[],[]],"norders":1670,"vars":[{"part":[[0],[1,2],[3,4]],"body":["SEL R14, RZ, 0x1, !P1","CS2R.32 R11, SR_CLOCKLO","LEA.LO R11, PT, R11, 0x1, 0x6","ELECT P1, URZ, ~URZ","ULOP3.LUT UPT, UR0, UR62, 0x3f, URZ, 0xc0, !UPT","UIMAD.WIDE.U32 {UR0,UR1}, UPT, UR0, 0x10, {UR60,UR61}","@P1 STG.E [RZ+UR0+0x20], R11","@P1 STG.E.64 [RZ+UR0+0x28], {R12,R13}","ISETP.NE.AND P1, PT, R14, RZ, PT","UIADD3 UR62, UPT, UPT, UR62, 0x1, URZ"],"need":[0,0,2,1,0,16,44,40,201,16],"edges":[[0,3,1,"fix"],[0,8,6,"fix"],[1,2,4,"fix"],[1,6,4,"fix"],[2,6,4,"fix"],[3,6,13,"fix"],[3,7,13,"fix"],[3,8,2,"fix"],[4,5,4,"fix"],[4,6,12,"fix"],[4,7,12,"fix"],[4,9,1,"fix"],[5,6,8,"fix"],[5,7,8,"fix"],[6,8,1,"fix"],[7,8,1,"fix"]],"rel":[30,30,30,30,30,30,14,16,30,30],"claim":[0,0,0,0,0,0,1,1,0,0],"root":29,"greedy":[4,5,1,2,0,3,7,6,8,9],"n":1670,"cmin":31,"c":"HHIGGGHGHGIIJHHHIHIHMMNLLLMLNMJIMLGGHFFFGFGFDDECCCDCDCDDECCCDCFFFGDCFDCDCFHHIGGGHGHGIIJHHHIHJIIHJIEEFDDDEDEDEEFDDDEDGGGHEDGEDEDGJJKIIIJIKJIIJHHHIHKKKLIHKKJJILHGIHFEFEHJIIHKGGHFFFGFGFCCDBBBCBDCCCDBBBCBEEEFCBECBCBEDDECCCDCEDBBCAAABADDDEBADDCBADCCDAAACADDDECADHHHHIDADHEDBADCADHHHIGGGHGHGIIJHHHIHJIIHJIDDECCCDCDCDDECCCDCFFFGDCFDCDCFHHIGGGHGIHGGHFFFGFIIIJGFIIHHGJHGIHEDEDGHGGFIDDECCCDCEDCCDBBBCBEEEFCBEDCCBECCDBBBCBEEEFCBEIIIIJCBEIEDCBECBEILLMKKKLKMLHHIGGGHGJJJKHGJLKIHKGGHFFFGFIIIJGFIMMMMNGFIMMLIHKHGJNIHJIEDEDGIHGFIEDDCFDCFJLKHGJGFIMFFGEEEFEFEGGHFFFGFGFKKLJJJKJLKHGKJEEFDDDEDEDDDECCCDCDCDDECCCDCFFFGDCFDCDCFFFGEEEFEFEIIJHHHIHJIGFIHEEFDDDEDEDEEFDDDEDGGGHEDGEDEDGJJKIIIJIKJIIJHHHIHKKKLIHKKJJILGFIHFEFEHJIIHKHHIGGGHGHGIIJHHHIHIHMMNLLLMLNMJIMLHHIGGGHGHGKKLJJJKJLKIHKJLLMKKKLKMLMLIHKJLKFFGEEEFEFEGGHFFFGFHGGFHGDDECCCDCDCDDECCCDCFFFGDCFDCDCFHHIGGGHGIHGGHFFFGFIIIJGFIIHHGJFEGFEDEDGHGGFIHHIGGGHGHGIIJHHHIHJIIHJIHHIGGGHGIHIHHGIHIHJJKIIIJIKJHHIGGGHGJJJKHGJJIIHKJJKIIIJIKJJIKJIHKKJGFHGEDEDGHGGFIHGIHHGJIHGJJIIIJHHHIHIHJJKIIIJIKJJIKJEEFDDDEDEDEEFDDDEDGGGHEDGEDEDGIIJHHHIHJIFFGEEEFEHHHIFEHIHGFIIHJIFEFEHIHGFIDDECCCDCEDCCDBBBCBEEEFCBEDCCBECCDBBBCBEEEFCBEIIIIJCBEIEDCBECBEIKKLJJJKJLKGGHFFFGFIIIJGFIKJHGJFFGEEEFEHHHIFEHLLLLMFEHLLKHGJGFIMIHJIEDEDGIHFEHEDDCFDCFJKJGFIFEHLGGHFFFGFGFHHIGGGHGIHHGIHEEFDDDEDEDEEFDDDEDGGGHEDGEDEDGGGHFFFGFHGFFGEEEFEHHHIFEHHGGFIGFHGFEFEHHGGFIIIJHHHIHIHJJKIIIJIKJJIKJIIJHHHIHJIJIIHJIJIIIJHHHIHJIGGHFFFGFIIIJGFIIHHGJIIJHHHIHJIIHJIHGJJIGFHGEDEDGGFFEHIHJIIHIHGFIIHMMNLLLMLNMIIJHHHIHKKKLIHKMLJILGGHFFFGFIIIJGFIMMMMNGFIMMLIHKHGJNKKLJJJKJLKIIJHHHIHKKKLIHKKJJILMMNLLLMLNMMLKJIHKMLNMJILHGJNLKJILNMJIKJFEFEHJIGFIEDDCFDCFJKJGFIFEHLHGIHFEFEHHGGFIJIKJJIIHGFIJIMLIHKGFIMKJIHKML"},{"part":[[0],[1],[2],[3],[4]],"body":["SEL R17, RZ, 0x1, !P1","CS2R.32 R18, SR_CLOCKLO","LEA.LO R19, PT, R18, 0x1, 0x6","ELECT P1, URZ, ~URZ","ULOP3.LUT UPT, UR2, UR62, 0x3f, URZ, 0xc0, !UPT","UIMAD.WIDE.U32 {UR0,UR1}, UPT, UR2, 0x10, {UR60,UR61}","@P1 STG.E [RZ+UR0+0x20], R19","@P1 STG.E.64 [RZ+UR0+0x28], {R12,R13}","ISETP.NE.AND P1, PT, R17, RZ, PT","UIADD3 UR62, UPT, UPT, UR62, 0x1, URZ"],"need":[0,0,2,1,0,16,44,40,201,16],"edges":[[0,3,1,"fix"],[0,8,6,"fix"],[1,2,4,"fix"],[2,6,4,"fix"],[3,6,13,"fix"],[3,7,13,"fix"],[3,8,2,"fix"],[4,5,4,"fix"],[4,9,1,"fix"],[5,6,8,"fix"],[5,7,8,"fix"],[6,8,1,"fix"],[7,8,1,"fix"]],"rel":[30,30,30,30,30,30,14,16,30,30],"claim":[0,0,0,0,0,0,1,1,0,0],"root":29,"greedy":[4,5,1,2,0,3,7,6,8,9],"n":1670,"cmin":31,"c":"HHIGGGHGHGIIJHHHIHIHMMNLLLMLNMJIMLGGHFFFGFGFDDECCCDCDCDDECCCDCFFFGDCFDCDCFHHIGGGHGHGIIJHHHIHJIIHJIEEFDDDEDEDEEFDDDEDGGGHEDGEDEDGJJKIIIJIKJIIJHHHIHKKKLIHKKJJILHGIHFEFEHJIIHKGGHFFFGFGFCCDBBBCBDCCCDBBBCBEEEFCBECBCBEDDECCCDCEDBBCAAABADDDEBADDCBADCCDAAACADDDECADHHHHIDADHEDBADCADHHHIGGGHGHGIIJHHHIHJIIHJIDDECCCDCDCDDECCCDCFFFGDCFDCDCFHHIGGGHGIHGGHFFFGFIIIJGFIIHHGJHGIHEDEDGHGGFIDDECCCDCEDCCDBBBCBEEEFCBEDCCBECCDBBBCBEEEFCBEIIIIJCBEIEDCBECBEILLMKKKLKMLHHIGGGHGJJJKHGJLKIHKGGHFFFGFIIIJGFIMMMMNGFIMMLIHKHGJNIHJIEDEDGIHGFIEDDCFDCFJLKHGJGFIMFFGEEEFEFEGGHFFFGFGFKKLJJJKJLKHGKJEEFDDDEDEDDDECCCDCDCDDECCCDCFFFGDCFDCDCFFFGEEEFEFEIIJHHHIHJIGFIHEEFDDDEDEDEEFDDDEDGGGHEDGEDEDGJJKIIIJIKJIIJHHHIHKKKLIHKKJJILGFIHFEFEHJIIHKHHIGGGHGHGIIJHHHIHIHMMNLLLMLNMJIMLHHIGGGHGHGKKLJJJKJLKIHKJLLMKKKLKMLMLIHKJLKFFGEEEFEFEGGHFFFGFHGGFHGDDECCCDCDCDDECCCDCFFFGDCFDCDCFHHIGGGHGIHGGHFFFGFIIIJGFIIHHGJFEGFEDEDGHGGFIHHIGGGHGHGIIJHHHIHJIIHJIHHIGGGHGIHIHHGIHIHJJKIIIJIKJHHIGGGHGJJJKHGJJIIHKJJKIIIJIKJJIKJIHKKJGFHGEDEDGHGGFIHGIHHGJIHGJJIIIJHHHIHIHJJKIIIJIKJJIKJEEFDDDEDEDEEFDDDEDGGGHEDGEDEDGIIJHHHIHJIFFGEEEFEHHHIFEHIHGFIIHJIFEFEHIHGFIDDECCCDCEDCCDBBBCBEEEFCBEDCCBECCDBBBCBEEEFCBEIIIIJCBEIEDCBECBEIKKLJJJKJLKGGHFFFGFIIIJGFIKJHGJFFGEEEFEHHHIFEHLLLLMFEHLLKHGJGFIMIHJIEDEDGIHFEHEDDCFDCFJKJGFIFEHLGGHFFFGFGFHHIGGGHGIHHGIHEEFDDDEDEDEEFDDDEDGGGHEDGEDEDGGGHFFFGFHGFFGEEEFEHHHIFEHHGGFIGFHGFEFEHHGGFIIIJHHHIHIHJJKIIIJIKJJIKJIIJHHHIHJIJIIHJIJIIIJHHHIHJIGGHFFFGFIIIJGFIIHHGJIIJHHHIHJIIHJIHGJJIGFHGEDEDGGFFEHIHJIIHIHGFIIHMMNLLLMLNMIIJHHHIHKKKLIHKMLJILGGHFFFGFIIIJGFIMMMMNGFIMMLIHKHGJNKKLJJJKJLKIIJHHHIHKKKLIHKKJJILMMNLLLMLNMMLKJIHKMLNMJILHGJNLKJILNMJIKJFEFEHJIGFIEDDCFDCFJKJGFIFEHLHGIHFEFEHHGGFIJIKJJIIHGFIJIMLIHKGFIMKJIHKML"}],"named":{"exact":{"v":0,"order":[0,3,4,1,9,5,2,7,6,8],"cost":31},"greedy":{"v":0,"order":[4,5,1,2,0,3,7,6,8,9],"cost":42},"best":{"v":0,"order":[0,3,4,1,9,5,2,7,6,8],"cost":31}},"events":[["start","greedy",0,5250,null,null,null,null,null,8160],["node","greedy",0,5280,[],null,null,null,null,null],["node","greedy",0,5310,[4],null,null,null,null,null],["node","greedy",0,5340,[4,5],null,null,null,null,null],["node","greedy",0,5370,[4,5,1],null,null,null,null,null],["node","greedy",0,5400,[4,5,1,2],null,null,null,null,null],["node","greedy",0,5430,[4,5,1,2,0],null,null,null,null,null],["node","greedy",0,5460,[4,5,1,2,0,3],null,null,null,null,null],["node","greedy",0,5490,[4,5,1,2,0,3,7],null,null,null,null,null],["node","greedy",0,5520,[4,5,1,2,0,3,7,6],null,null,null,null,null],["node","greedy",0,5550,[4,5,1,2,0,3,7,6,8],null,null,null,null,null],["leaf","greedy",0,5680,[4,5,1,2,0,3,7,6,8,9],null,null,42,true,null],["end","greedy",0,5680,null,null,42,null,null,null],["start","greedy",1,5710,null,null,42,null,null,8160],["node","greedy",1,5740,[],null,42,null,null,null],["node","greedy",1,5770,[4],29,42,null,null,null],["node","greedy",1,5800,[4,5],29,42,null,null,null],["node","greedy",1,5830,[4,5,1],29,42,null,null,null],["node","greedy",1,5860,[4,5,1,2],29,42,null,null,null],["node","greedy",1,5890,[4,5,1,2,0],29,42,null,null,null],["node","greedy",1,5920,[4,5,1,2,0,3],30,42,null,null,null],["prune","greedy",1,5950,[4,5,1,2,0,3,7],42,42,null,null,null],["end","greedy",1,5950,null,null,42,null,null,null],["start","optimal",1,5950,null,null,31,null,null,8160],["node","optimal",1,5980,[],null,31,null,null,null],["node","optimal",1,6010,[4],29,31,null,null,null],["node","optimal",1,6040,[4,1],29,31,null,null,null],["node","optimal",1,6070,[4,1,9],29,31,null,null,null],["node","optimal",1,6100,[4,1,9,0],29,31,null,null,null],["node","optimal",1,6130,[4,1,9,0,5],29,31,null,null,null],["node","optimal",1,6160,[4,1,9,0,5,2],29,31,null,null,null],["node","optimal",1,6190,[4,1,9,0,5,2,3],29,31,null,null,null],["prune","optimal",1,6220,[4,1,9,0,5,2,3,7],36,31,null,null,null],["prune","optimal",1,6250,[4,1,9,0,5,2,3,6],37,31,null,null,null],["node","optimal",1,6280,[4,1,9,0,5,3],29,31,null,null,null],["node","optimal",1,6310,[4,1,9,0,5,3,2],29,31,null,null,null],["prune","optimal",1,6340,[4,1,9,0,5,3,2,7],35,31,null,null,null],["prune","optimal",1,6370,[4,1,9,0,5,3,2,6],36,31,null,null,null],["prune","optimal",1,6400,[4,1,9,0,5,3,7],38,31,null,null,null],["node","optimal",1,6430,[4,1,9,0,3],30,31,null,null,null],["node","optimal",1,6460,[4,1,9,0,3,5],29,31,null,null,null],["node","optimal",1,6490,[4,1,9,0,3,5,2],29,31,null,null,null],["prune","optimal",1,6520,[4,1,9,0,3,5,2,7],34,31,null,null,null],["prune","optimal",1,6550,[4,1,9,0,3,5,2,6],35,31,null,null,null],["prune","optimal",1,6580,[4,1,9,0,3,5,7],37,31,null,null,null],["prune","optimal",1,6610,[4,1,9,0,3,2],31,31,null,null,null],["prune","optimal",1,6640,[4,1,9,0,2],31,31,null,null,null],["node","optimal",1,6670,[4,1,9,5],29,31,null,null,null],["node","optimal",1,6700,[4,1,9,5,2],29,31,null,null,null],["node","optimal",1,6730,[4,1,9,5,2,0],29,31,null,null,null],["node","optimal",1,6760,[4,1,9,5,2,0,3],29,31,null,null,null],["prune","optimal",1,6790,[4,1,9,5,2,0,3,7],38,31,null,null,null],["prune","optimal",1,6820,[4,1,9,5,2,0,3,6],39,31,null,null,null],["node","optimal",1,6850,[4,1,9,5,0],29,31,null,null,null],["node","optimal",1,6880,[4,1,9,5,0,3],29,31,null,null,null],["node","optimal",1,6910,[4,1,9,5,0,3,2],29,31,null,null,null],["prune","optimal",1,6940,[4,1,9,5,0,3,2,7],36,31,null,null,null],["prune","optimal",1,6970,[4,1,9,5,0,3,2,6],37,31,null,null,null],["prune","optimal",1,7000,[4,1,9,5,0,3,7],39,31,null,null,null],["node","optimal",1,7030,[4,1,9,5,0,2],29,31,null,null,null],["node","optimal",1,7060,[4,1,9,5,0,2,3],29,31,null,null,null],["prune","optimal",1,7090,[4,1,9,5,0,2,3,7],38,31,null,null,null],["prune","optimal",1,7120,[4,1,9,5,0,2,3,6],39,31,null,null,null],["prune","optimal",1,7150,[4,1,9,2],31,31,null,null,null],["node","optimal",1,7180,[4,1,0],29,31,null,null,null],["node","optimal",1,7210,[4,1,0,5],29,31,null,null,null],["node","optimal",1,7240,[4,1,0,5,2],29,31,null,null,null],["node","optimal",1,7270,[4,1,0,5,2,3],29,31,null,null,null],["node","optimal",1,7300,[4,1,0,5,2,3,9],29,31,null,null,null],["prune","optimal",1,7330,[4,1,0,5,2,3,9,7],36,31,null,null,null],["prune","optimal",1,7360,[4,1,0,5,2,3,9,6],37,31,null,null,null],["prune","optimal",1,7390,[4,1,0,5,2,3,7],36,31,null,null,null],["prune","optimal",1,7420,[4,1,0,5,2,3,6],37,31,null,null,null],["node","optimal",1,7450,[4,1,0,5,2,9],29,31,null,null,null],["node","optimal",1,7480,[4,1,0,5,2,9,3],29,31,null,null,null],["prune","optimal",1,7510,[4,1,0,5,2,9,3,7],37,31,null,null,null],["prune","optimal",1,7540,[4,1,0,5,2,9,3,6],38,31,null,null,null],["node","optimal",1,7570,[4,1,0,5,3],29,31,null,null,null],["node","optimal",1,7600,[4,1,0,5,3,2],29,31,null,null,null],["node","optimal",1,7630,[4,1,0,5,3,2,9],29,31,null,null,null],["prune","optimal",1,7660,[4,1,0,5,3,2,9,7],35,31,null,null,null],["prune","optimal",1,7690,[4,1,0,5,3,2,9,6],36,31,null,null,null],["prune","optimal",1,7720,[4,1,0,5,3,2,7],35,31,null,null,null],["prune","optimal",1,7750,[4,1,0,5,3,2,6],36,31,null,null,null],["node","optimal",1,7780,[4,1,0,5,3,9],29,31,null,null,null],["node","optimal",1,7810,[4,1,0,5,3,9,2],29,31,null,null,null],["prune","optimal",1,7840,[4,1,0,5,3,9,2,7],35,31,null,null,null],["prune","optimal",1,7870,[4,1,0,5,3,9,2,6],36,31,null,null,null],["prune","optimal",1,7900,[4,1,0,5,3,9,7],38,31,null,null,null],["prune","optimal",1,7930,[4,1,0,5,3,7],38,31,null,null,null],["node","optimal",1,7960,[4,1,0,5,9],29,31,null,null,null],["node","optimal",1,7990,[4,1,0,5,9,2],29,31,null,null,null],["node","optimal",1,8020,[4,1,0,5,9,2,3],29,31,null,null,null],["prune","optimal",1,8050,[4,1,0,5,9,2,3,7],37,31,null,null,null],["prune","optimal",1,8080,[4,1,0,5,9,2,3,6],38,31,null,null,null],["node","optimal",1,8110,[4,1,0,5,9,3],29,31,null,null,null],["node","optimal",1,8140,[4,1,0,5,9,3,2],29,31,null,null,null],["prune","optimal",1,8170,[4,1,0,5,9,3,2,7],36,31,null,null,null],["budget","optimal",1,8170,[4,1,0,5,9,3,2],null,null,null,null,null],["budget","optimal",1,8170,[4,1,0,5,9,3],null,null,null,null,null],["budget","optimal",1,8170,[4,1,0],null,null,null,null,null],["budget","optimal",1,8170,[4,1],null,null,null,null,null],["budget","optimal",1,8170,[4],null,null,null,null,null],["budget","optimal",1,8170,[],null,null,null,null,null],["end","optimal",1,8170,null,null,31,null,null,null]],"w0":3160,"rep":{"search_ms":4.692,"dfs_nodes":93,"pruned":36,"proven":false,"capped_in":"optimal","work":5010,"free_sb":[0,1,2,3,4,5],"kernel_busy_sb":[],"free":{"R":13,"UR":53,"P":0,"UP":7},"m4_cycles":195},"at5000":[5000,31,42,false,"optimal",5010,93]}}};

  const opOf = (text) => text.replace(/^@!?U?P[T0-9]+\s+/, '').split(/[ .]/)[0];

  // =====================================================================
  // The Algorithm 1 explorer: D2 orders on the dependency graph, D1 assignments, the cost of every order,
  // and a replay of the logged search against its work budget.
  // =====================================================================
  function initExplorer(host) {
    const dagSvg = $('.dag svg', host), histSvg = $('.hist svg', host), meterSvg = $('.meter svg', host);
    const orderEl = $('.ax-order', host), siteEl = $('.ax-site', host), evEl = $('.ax-ev', host), readEl = $('.ax-read', host);
    const siteBtns = $$('[data-site]', host), varBtns = $$('[data-var]', host);
    const replayBtn = $('[data-act="replay"]', host);
    let key = 'tile', vi = 0, order = [], ghost = null, ev = -1, evTimer = null;
    const cache = {};

    const SITE = {
      tile: bi('DeepGEMM k512 trace-pp, <code>c.tile_done</code> (before index 1100): a timestamp record, 7 instructions, 5 values, 150 valid orders. SB0 and SB1 are held by the kernel; SB2–SB5 are free.',
        'DeepGEMM k512 trace-pp，<code>c.tile_done</code>（索引 1100 之前）：一条时间戳记录，7 条指令、5 个值、150 个合法顺序。SB0 和 SB1 被 kernel 占用；SB2–SB5 空闲。'),
      exch: bi('DeepGEMM k512 trace-mem, <code>SYNCS.EXCH.64</code> (before index 38): a 32-bit uniform value record, 10 instructions, 6 values. The template shares R0 between the clock, the packed word and the value copy; here D1 decides the cost.',
        'DeepGEMM k512 trace-mem，<code>SYNCS.EXCH.64</code>（索引 38 之前）：一条 32 位 uniform 值记录，10 条指令、6 个值。模板让时钟、打包后的字和值的拷贝共用 R0；这里由 D1 决定开销。'),
      smax: bi('t1_softmax trace-mem, <code>LDGSTS.E.BYPASS.128</code> (before index 42): a 64-bit value record in the psave form. No predicate is dead, so the probe saves P1 in R14, elects on it and restores it; <code>ELECT P1</code> writes a fixed register, not a value, so the greedy price (Eq. 4) sees no value edge from it and prices it at 0.',
        't1_softmax trace-mem，<code>LDGSTS.E.BYPASS.128</code>（索引 42 之前）：psave 形式的 64 位值记录。没有死谓词，所以探针把 P1 保存到 R14，用它做 elect，再恢复它；<code>ELECT P1</code> 写的是固定寄存器而不是值，贪心定价（式 4）看不到从它出发的值依赖边，给它定价 0。')
    };

    function prep(k) {
      if (cache[k]) return cache[k];
      const s = DATA.sites[k], n = s.tmpl.length;
      const defs = s.tmpl.map(() => []), uses = s.tmpl.map(() => []);
      s.values.forEach((v, id) => { defs[v.d].push(id); v.uses.forEach((u) => { if (!uses[u].includes(id)) uses[u].push(id); }); });
      const topo = [];
      { const done = new Set(); while (topo.length < n) { for (let q = 0; q < n; q++) { if (!done.has(q) && s.preds[q].every((p) => done.has(p))) { topo.push(q); done.add(q); break; } } } }
      const vars = s.vars.map((v) => {
        const blockOf = {};
        v.part.forEach((b, bIdx) => b.forEach((x) => { blockOf[x] = bIdx; }));
        // search._occupy: a write needs its register block free (the value in it has no uses left)
        const occupy = (q, occ, left) => {
          const dying = new Set();
          for (const id of uses[q]) { left[id]--; if (left[id] === 0) dying.add(id); }
          for (const id of defs[q]) { const cur = occ[blockOf[id]]; if (cur != null && !dying.has(cur)) return false; }
          for (const id of dying) if (occ[blockOf[id]] === id) occ[blockOf[id]] = null;
          for (const id of defs[q]) occ[blockOf[id]] = left[id] > 0 ? id : null;
          return true;
        };
        const left0 = {}; s.values.forEach((x, id) => { left0[id] = x.uses.length; });
        const orders = [];
        const rec = (issued, occ, left, ord) => {
          if (ord.length === n) { orders.push(ord.slice()); return; }
          for (let q = 0; q < n; q++) {
            if ((issued >> q) & 1 || (v.need[q] & issued) !== v.need[q]) continue;
            const o2 = Object.assign({}, occ), l2 = Object.assign({}, left);
            if (!occupy(q, o2, l2)) continue;
            ord.push(q); rec(issued | (1 << q), o2, l2, ord); ord.pop();
          }
        };
        rec(0, {}, left0, []);
        const idx = new Map(orders.map((o, i) => [o.join(','), i]));
        const cost = orders.map((_, i) => v.cmin + A64.indexOf(v.c[i]));
        const edge = {};
        v.edges.forEach(([a, b, lat, kind]) => { edge[a + ',' + b] = [lat, kind]; });
        // Eq. 4 over the value edges only (search.greedy_order)
        const price = new Array(n).fill(0);
        topo.slice().reverse().forEach((q) => {
          let p = 0;
          s.raw[q].forEach((j) => { const e = edge[q + ',' + j]; if (e) p = Math.max(p, (e[1] === 'wr' || e[1] === 'rd' ? v.rel[q] : e[0]) + price[j]); });
          if (v.claim[q]) p = Math.max(p, v.rel[q]);
          price[q] = p;
        });
        const greedy = [];
        { const left = new Set(Array.from({ length: n }, (_, q) => q)); while (left.size) { const mask = greedy.reduce((a, q) => a | (1 << q), 0); let best = -1; left.forEach((q) => { if ((v.need[q] & mask) === v.need[q] && (best < 0 || price[q] > price[best] || (price[q] === price[best] && q < best))) best = q; }); greedy.push(best); left.delete(best); } }
        let mn = Infinity, mx = -Infinity, imin = 0, imax = 0;
        cost.forEach((c, i) => { if (c < mn) { mn = c; imin = i; } if (c > mx) { mx = c; imax = i; } });
        const hist = {};
        cost.forEach((c) => { hist[c] = (hist[c] || 0) + 1; });
        return { v, orders, idx, cost, edge, price, greedy, occupy, left0, min: mn, max: mx, imin, imax, hist };
      });
      // register-sharing edges: dependencies of the shared assignment that the finest one does not have
      const shareEdges = [];
      if (vars.length > 1) {
        const e1 = vars[1].edge;
        s.vars[0].edges.forEach(([a, b, lat, kind]) => { if (!e1[a + ',' + b] && a < b && (kind === 'rd' || kind === 'wr')) shareEdges.push([a, b, lat, kind]); });
      }
      const r = { s, n, defs, uses, vars, shareEdges, topo };
      cache[k] = r;
      return r;
    }

    function shortLabel(text) {
      let g = '', t = text;
      const m = t.match(/^(@!?U?P[T0-9]+)\s+/);
      if (m) { g = m[1] + ' '; t = t.slice(m[0].length); }
      const sp = t.indexOf(' ');
      const op = (sp < 0 ? t : t.slice(0, sp)).split('.').slice(0, 2).join('.');
      const ops = sp < 0 ? [] : t.slice(sp + 1).split(/,\s*(?![^{]*})/).map((x) => x.trim());
      if (/^STG/.test(op)) return `${g}${op} ← ${(ops[ops.length - 1] || '').replace(/[{}]/g, '')}`;
      const dst = ops.find((x) => !/^(U?PT|RZ|URZ)$/.test(x)) || '';
      return `${g}${op} ${dst.replace(/[{}]/g, '').replace(/,.*$/, '')}`;
    }

    function replay(ord) {                      // occupancy state after a partial order (null if invalid)
      const P = prep(key), V = P.vars[vi];
      const occ = {}, left = Object.assign({}, V.left0);
      for (const q of ord) if (!V.occupy(q, occ, left)) return null;
      return { occ, left };
    }

    // ---------- the dependency graph ----------
    function drawDag() {
      const P = prep(key), V = P.vars[vi], n = P.n;
      const need = V.v.need;
      const preds = Array.from({ length: n }, (_, q) => Array.from({ length: n }, (_, p) => p).filter((p) => (need[q] >> p) & 1));
      const layer = new Array(n).fill(0);
      P.topo.forEach((q) => { preds[q].forEach((p) => { layer[q] = Math.max(layer[q], layer[p] + 1); }); });
      const L = Math.max(...layer) + 1;
      const byL = Array.from({ length: L }, () => []);
      for (let q = 0; q < n; q++) byL[layer[q]].push(q);
      const W = 520, BW = 124, BH = 38, colW = (W - BW) / Math.max(L - 1, 1);
      const rows = Math.max(...byL.map((a) => a.length));
      const H = Math.max(24 + rows * (BH + 14) + 10 + (vi === 0 && P.shareEdges.length ? 30 : 0), 150);
      dagSvg.setAttribute('viewBox', `0 0 ${W} ${H}`);
      dagSvg.innerHTML = '';
      const pos = [];
      byL.forEach((arr, l) => arr.forEach((q, j) => { pos[q] = { x: l * colW, y: 16 + j * (BH + 14) + (rows - arr.length) * (BH + 14) / 2 }; }));
      const defs = S('defs', null, dagSvg);
      [['dag-a', 'mk-fix'], ['dag-b', 'mk-share']].forEach(([id, cls]) => {
        const mk = S('marker', { id, viewBox: '0 0 8 8', refX: 7, refY: 4, markerWidth: 6, markerHeight: 6, orient: 'auto' }, defs);
        S('path', { d: 'M0,0 L8,4 L0,8 z', class: cls }, mk);
      });
      const shown = ghost || order;
      const issued = new Set(shown);
      const mask = shown.reduce((a, q) => a | (1 << q), 0);
      const edgeLbl = (a, b) => { const e = V.edge[a + ',' + b]; if (!e) return ''; return e[1] === 'wr' || e[1] === 'rd' ? `${e[1]} ${V.v.rel[a]}` : String(e[0]); };
      const labels = [];
      const inc = Array.from({ length: n }, () => []);
      for (let q = 0; q < n; q++) preds[q].forEach((p) => inc[q].push(p));
      if (vi === 0) P.shareEdges.forEach(([a, b]) => { if (layer[a] < layer[b]) inc[b].push(a); });
      inc.forEach((arr) => arr.sort((u, w) => pos[u].y - pos[w].y));
      const curve = (a, b) => {
        const A = pos[a], B = pos[b], k = inc[b].indexOf(a), m = inc[b].length;
        const x1 = A.x + BW, y1 = A.y + BH / 2, x2 = B.x - 2, y2 = B.y + BH * (k + 1) / (m + 1);
        const mx = (x1 + x2) / 2;
        return { d: `M${x1},${y1} C${mx},${y1} ${mx},${y2} ${x2},${y2}`, lx: x2 - 12, ly: y2 - 3 };
      };
      for (let q = 0; q < n; q++) preds[q].forEach((p) => {
        const c = curve(p, q);
        S('path', { d: c.d, class: 'e-fix', 'marker-end': 'url(#dag-a)' }, dagSvg);
        const lb = edgeLbl(p, q);
        if (lb) labels.push([c.lx, c.ly, lb, 'muted']);
      });
      if (vi === 0) P.shareEdges.forEach(([a, b, lat, kind]) => {
        if (layer[a] >= layer[b]) {
          const A = pos[a], B = pos[b];
          const d = `M${A.x + BW / 2},${A.y + BH} C${A.x + BW / 2},${A.y + BH + 30} ${B.x + BW / 2},${B.y + BH + 30} ${B.x + BW / 2},${B.y + BH + 2}`;
          S('path', { d, class: 'e-share', 'marker-end': 'url(#dag-b)' }, dagSvg);
          ST(dagSvg, { x: (A.x + B.x) / 2 + BW / 2, y: Math.max(A.y, B.y) + BH + 26, class: 't-sm asy strong', 'text-anchor': 'middle' }, `${kind} ${V.v.rel[a]}: shared register`, `${kind} ${V.v.rel[a]}：共用寄存器`);
        } else {
          const c = curve(a, b);
          S('path', { d: c.d, class: 'e-share', 'marker-end': 'url(#dag-b)' }, dagSvg);
          labels.push([c.lx, c.ly, `${kind} ${V.v.rel[a]}`, 'asy strong']);
        }
      });
      // register blocks shared by more than one value get a colour tag
      const shared = V.v.part.filter((b) => b.length > 1);
      const blockColor = {};
      shared.forEach((b, i) => b.forEach((id) => { blockColor[id] = i; }));
      const body = V.v.body;
      const st = ghost ? null : replay(order);
      for (let q = 0; q < n; q++) {
        const eligible = !ghost && st && !issued.has(q) && (need[q] & mask) === need[q] && V.occupy(q, Object.assign({}, st.occ), Object.assign({}, st.left));
        const cls = 'nd' + (issued.has(q) ? (ghost ? ' ghost' : ' issued') : eligible ? ' elig' : ' blocked');
        const g = S('g', { class: cls, transform: `translate(${pos[q].x},${pos[q].y})` }, dagSvg);
        if (eligible) { g.setAttribute('tabindex', '0'); g.setAttribute('role', 'button'); g.setAttribute('aria-label', 'issue ' + body[q]); }
        S('rect', { class: 'box', x: 0, y: 0, width: BW, height: BH, rx: 4 }, g);
        S('text', { x: 6, y: 15, class: 't-sm strong' }, g, shortLabel(body[q]).slice(0, 20));
        S('text', { x: 6, y: 30, class: 't-sm muted' }, g, `p=${V.price[q]}`);
        const dv = P.defs[q].find((id) => blockColor[id] != null);
        if (dv != null) S('rect', { x: BW - 9, y: 3, width: 6, height: 6, rx: 1, class: 'regtag', style: `fill: var(--r${blockColor[dv] % 4}); stroke: var(--r${blockColor[dv] % 4})` }, g);
        const at = shown.indexOf(q);
        if (at >= 0) {
          S('circle', { cx: BW - 10, cy: BH - 10, r: 7.5, class: 'badge' }, g);
          S('text', { x: BW - 10, y: BH - 6.5, class: 't-sm on-badge', 'text-anchor': 'middle' }, g, String(at + 1));
        }
        tipOn(g, () => `${esc(body[q])}<br>${bi(`greedy price p = ${V.price[q]} (Eq. 4)`, `贪心定价 p = ${V.price[q]}（式 4）`)}`);
        if (eligible) {
          const go = () => { order.push(q); hideTip(); render(); };
          g.addEventListener('click', go);
          g.addEventListener('keydown', (e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); go(); } });
        }
      }
      labels.forEach(([x, y, t, cls]) => {
        const w = 6.4 * t.length + 6;
        S('rect', { x: x - w / 2, y: y - 9, width: w, height: 12, rx: 2, class: 'lblbg' }, dagSvg);
        S('text', { x, y, class: 't-sm ' + cls, 'text-anchor': 'middle' }, dagSvg, t);
      });
    }

    // ---------- every valid order, by cost ----------
    function drawHist() {
      const P = prep(key), s = P.s;
      const lo = Math.min(...P.vars.map((V) => Math.min(V.min, Math.floor(V.v.root)))), hi = Math.max(...P.vars.map((V) => V.max));
      const W = 360, X0 = 34, X1 = 350, PH = 118, gap = 34, top = 22;
      const H = top + P.vars.length * (PH + gap) + 14;
      histSvg.setAttribute('viewBox', `0 0 ${W} ${H}`);
      histSvg.innerHTML = '';
      const bw = (X1 - X0) / (hi - lo + 1);
      const sx = (c) => X0 + (c - lo) * bw;
      const curIdx = order.length === P.n ? P.vars[vi].idx.get(order.join(',')) : undefined;
      P.vars.forEach((V, k) => {
        const y0 = top + k * (PH + gap), yb = y0 + PH - 16;
        S('rect', { x: 0, y: y0 - 16, width: W, height: PH + 14, rx: 4, class: 'panel' + (k === vi ? ' on' : '') }, histSvg);
        ST(histSvg, { x: 6, y: y0 - 3, class: 't-sm' + (k === vi ? ' strong' : ' muted') },
          `${k === 0 ? 'template registers' : 'finest, cold registers'} · ${num(V.orders.length)} orders`,
          `${k === 0 ? '模板寄存器' : '最细、冷寄存器'} · ${num(V.orders.length)} 个顺序`);
        const maxC = Math.max(...Object.values(V.hist));
        for (let c = lo; c <= hi; c++) {
          const cnt = V.hist[c] || 0;
          if (!cnt) continue;
          const h = Math.max(1.5, (PH - 44) * cnt / maxC);
          const cur = k === vi && curIdx !== undefined && V.cost[curIdx] === c;
          const r = S('rect', { x: sx(c) + 0.5, y: yb - h, width: Math.max(bw - 1, 1), height: h, class: 'hb' + (c === V.min ? ' min' : '') + (cur ? ' cur' : '') }, histSvg);
          tipOn(r, bi(`cost ${c}: ${num(cnt)} order${cnt > 1 ? 's' : ''}`, `开销 ${c}：${num(cnt)} 个顺序`));
        }
        S('line', { x1: X0, y1: yb + 0.5, x2: X1, y2: yb + 0.5, class: 'axis' }, histSvg);
        const rb = V.v.root;
        S('line', { x1: sx(rb), y1: y0 + 4, x2: sx(rb), y2: yb, class: 'lb' }, histSvg);
        ST(histSvg, { x: sx(rb) + 3, y: y0 + 12, class: 't-sm muted' }, `root bound ${rb}`, `根下界 ${rb}`);
        const marks = [];
        if (s.named.exact.v === k) marks.push(['exact', s.named.exact.cost]);
        const gi = V.idx.get(V.greedy.join(','));
        marks.push(['greedy', gi === undefined ? null : V.cost[gi]]);
        if (s.named.best.v === k) marks.push(['best', s.named.best.cost]);
        const byCost = {};
        marks.forEach(([nm, c]) => {
          if (c == null) { ST(histSvg, { x: X1, y: y0 + 26, class: 't-sm asy', 'text-anchor': 'end' }, 'greedy order: invalid here', '贪心顺序：此分配下不合法'); return; }
          (byCost[c] = byCost[c] || []).push(nm);
        });
        Object.keys(byCost).forEach((c, j) => {
          const lx = sx(+c) + bw / 2, names = byCost[c];
          const cls = names.includes('best') ? 'mk-o' : names.includes('greedy') ? 'mk-g' : 'mk-exact';
          S('path', { d: `M${lx},${yb + 3} l-4.5,8 h9 z`, class: cls }, histSvg);
          const lbl = names.map((nm) => (nm === 'exact' ? 'exact' : nm === 'greedy' ? 'G' : 'opt')).join('·') + ' ' + c;
          const right = lx > X1 - 60;
          S('text', { x: right ? lx + 5 : lx - 5, y: yb + 22 + (j % 2) * 10, class: 't-sm strong', 'text-anchor': right ? 'end' : 'start' }, histSvg, lbl);
        });
        [lo, hi].forEach((c) => S('text', { x: sx(c) + bw / 2, y: yb + 12, class: 't-sm muted', 'text-anchor': 'middle' }, histSvg, String(c)));
      });
      ST(histSvg, { x: X1, y: H - 2, class: 't-sm muted', 'text-anchor': 'end' }, 'estimated cycles →', '估计周期 →');
    }

    // ---------- the order chips and the readouts ----------
    function drawOrder() {
      const P = prep(key), body = P.vars[vi].v.body;
      if (ghost) {
        orderEl.innerHTML = `<span class="muted">${bi('search:', '搜索：')}</span> ` + (ghost.length ? ghost.map((q) => `<span class="tok" title="${esc(body[q])}">${esc(opOf(body[q]))}</span>`).join('<span class="arr">→</span>') : `<span class="muted">${bi('(empty)', '（空）')}</span>`);
        return;
      }
      orderEl.innerHTML = order.length
        ? order.map((q, i) => `<span class="tok" title="${esc(body[q])}">${i + 1}·${esc(opOf(body[q]))}</span>`).join('<span class="arr">→</span>')
        : `<span class="muted">${bi('Click a green-edged instruction to start an order, or pick a preset below.', '点击绿框指令开始排一个顺序，或者在下面选一个预设。')}</span>`;
    }
    function drawRead() {
      const P = prep(key), s = P.s, V = P.vars[vi];
      let mine = bi('build an order', '请排出一个顺序'), mineS = `${order.length} / ${P.n}`;
      if (order.length === P.n) {
        const i = V.idx.get(order.join(','));
        if (i !== undefined) {
          const c = V.cost[i];
          const better = V.cost.filter((x) => x < c).length;
          mine = `${c} ${bi('cycles', '周期')}`;
          mineS = bi(`${num(better)} of ${num(V.orders.length)} orders are cheaper`, `${num(V.orders.length)} 个顺序中有 ${num(better)} 个更便宜`);
        }
      }
      const nm = s.named;
      const fact = (x) => { let f = 1; for (let i = 2; i <= x; i++) f *= i; return f; };
      const sb = s.rep;
      readEl.innerHTML = `
        <div class="readout key"><span class="k">${bi('This order', '当前顺序')}</span><span class="v">${mine}</span><span class="s">${mineS}</span></div>
        <div class="readout"><span class="k">${bi('Orders (D2)', '顺序（D2）')}</span><span class="v">${num(V.orders.length)}</span><span class="s">${bi(`of ${num(fact(P.n))} permutations; root bound ${V.v.root}`, `共 ${num(fact(P.n))} 种排列；根下界 ${V.v.root}`)}</span></div>
        <div class="readout"><span class="k">${bi('exact · greedy · optimal', 'exact · 贪心 · 最优')}</span><span class="v">${nm.exact.cost} · ${nm.greedy ? nm.greedy.cost : '–'} · ${nm.best.cost}</span><span class="s">${bi(`fenced planner at this site: ${sb.m4_cycles}`, `带围栏的规划器在此站点：${sb.m4_cycles}`)}</span></div>
        <div class="readout"><span class="k">${bi('Scoreboards (D3)', 'Scoreboard（D3）')}</span><span class="v">${bi('free', '空闲')} {${sb.free_sb.join(',')}}</span><span class="s">${sb.kernel_busy_sb.length ? bi(`kernel holds {${sb.kernel_busy_sb.join(',')}}: never waited on`, `kernel 占用 {${sb.kernel_busy_sb.join(',')}}：从不等待`) : bi('none held by the kernel here', '此处 kernel 未占用任何一个')}</span></div>`;
    }

    // ---------- replay of the logged search ----------
    const PH = { greedy: bi('greedy', '贪心'), optimal: bi('optimal', '最优'), relax: bi('relaxation', '松弛') };
    function evList() {
      const out = [];
      prep(key).s.events.forEach((e) => { if (e[0] === 'budget' && out.length && out[out.length - 1][0] === 'budget') return; out.push(e); });
      return out;
    }
    function seqText(seq) {
      const P = prep(key);
      return seq && seq.length ? seq.map((q) => opOf(P.s.tmpl[q])).join(' → ') : '∅';
    }
    function drawMeter() {
      const s = prep(key).s, E = evList();
      const w0 = s.w0;
      const lastW = E.length ? E[E.length - 1][3] - w0 : 0;
      const maxW = Math.max(BUDGET, lastW) * 1.04;
      const X0 = 8, X1 = 872, sx = (w) => X0 + (w / maxW) * (X1 - X0);
      meterSvg.innerHTML = '';
      const firstStart = E.find((e) => e[0] === 'start');
      const optStart = E.find((e) => e[0] === 'start' && e[1] !== 'greedy');
      const asgEnd = firstStart ? firstStart[3] - w0 : lastW;
      const grEnd = optStart ? optStart[3] - w0 : lastW;
      const bands = [[0, asgEnd, 'ph-asg', 'assignments', '构建分配'], [asgEnd, grEnd, 'ph-gr', 'greedy', '贪心'], [grEnd, lastW, 'ph-opt', 'optimal', '最优']];
      bands.forEach(([a, b, cls, en, zh]) => {
        if (b - a <= 0) return;
        S('rect', { x: sx(a), y: 16, width: Math.max(sx(b) - sx(a), 1), height: 16, class: cls }, meterSvg);
        if (sx(b) - sx(a) > 56) ST(meterSvg, { x: sx(a) + 4, y: 28, class: 't-sm' }, en, zh);
      });
      S('line', { x1: sx(BUDGET), y1: 8, x2: sx(BUDGET), y2: 40, class: 'bud' }, meterSvg);
      ST(meterSvg, { x: sx(BUDGET) - 4, y: 10, class: 't-sm strong', 'text-anchor': 'end' }, 'budget 5,000', '预算 5,000');
      S('line', { x1: sx(BUDGET / 2), y1: 12, x2: sx(BUDGET / 2), y2: 36, class: 'guide' }, meterSvg);
      ST(meterSvg, { x: sx(BUDGET / 2) + 3, y: 46, class: 't-sm muted' }, 'assignment share', '分配份额');
      S('text', { x: X0, y: 46, class: 't-sm muted' }, meterSvg, '0');
      ST(meterSvg, { x: sx(lastW), y: 54, class: 't-sm muted', 'text-anchor': 'end' }, `${num(lastW)}${lastW >= BUDGET ? ' (capped)' : ''}`, `${num(lastW)}${lastW >= BUDGET ? '（截断）' : ''}`);
      const cur = S('line', { x1: sx(0), y1: 12, x2: sx(0), y2: 36, class: 'cur' }, meterSvg);
      if (ev >= 0 && E[ev]) { const xx = sx(E[ev][3] - w0); cur.setAttribute('x1', xx); cur.setAttribute('x2', xx); } else cur.style.opacity = '0';
    }
    function evTextOf(e) {
      const [t, ph, v, w, seq, lb, inc, c, better] = e;
      const wu = num(w - prep(key).s.w0);
      const vn = v === 0 ? bi('template regs', '模板寄存器') : v === 1 ? bi('finest regs', '最细寄存器') : bi('relaxation', '松弛');
      const head = `<b>${PH[ph] || ph}</b> · ${vn} · ${wu} ${bi('units', '单位')} · `;
      if (t === 'start') return head + bi(`start, incumbent ${inc == null ? '–' : inc}`, `开始，当前最优 ${inc == null ? '–' : inc}`);
      if (t === 'node') return head + bi(`expand [${seqText(seq)}]${lb != null ? ` · bound ${lb} < ${inc}` : ''}`, `展开 [${seqText(seq)}]${lb != null ? ` · 下界 ${lb} < ${inc}` : ''}`);
      if (t === 'prune') return head + bi(`prune [${seqText(seq)}] · bound ${lb} ≥ incumbent ${inc}`, `剪枝 [${seqText(seq)}] · 下界 ${lb} ≥ 当前最优 ${inc}`);
      if (t === 'dom') return head + bi(`dominated [${seqText(seq)}]: an equivalent partial schedule was already expanded`, `被支配 [${seqText(seq)}]：等价的部分调度已经展开过`);
      if (t === 'leaf') return head + bi(`leaf [${seqText(seq)}] · cost ${c}${better ? ' · new incumbent' : ''}`, `叶子 [${seqText(seq)}] · 开销 ${c}${better ? ' · 新的当前最优' : ''}`);
      if (t === 'budget') return head + bi(`budget reached: keep ${inc == null ? 'the incumbent' : inc}, not proven`, `预算用尽：保留 ${inc == null ? '当前最优' : inc}，未证明`);
      if (t === 'end') return head + bi(`done, incumbent ${inc == null ? '–' : inc}`, `结束，当前最优 ${inc == null ? '–' : inc}`);
      return head;
    }
    function showEv() {
      const E = evList();
      if (ev < 0) {
        const s = prep(key).s, r = s.rep;
        const opt = s.events.some((e) => e[0] === 'start' && e[1] === 'optimal');
        evEl.innerHTML = bi(`${E.length} logged events, ${num(r.work)} work units, ${r.dfs_nodes} DFS nodes, ${r.search_ms} ms. The optimal phase ${opt ? 'runs' : 'never runs: the root bound already equals the incumbent'}. ${r.proven ? 'Proven optimal.' : `Capped in the ${r.capped_in} phase: the incumbent is kept, not proven.`}`,
          `共记录 ${E.length} 个事件、${num(r.work)} 个工作量单位、${r.dfs_nodes} 个 DFS 节点、${r.search_ms} ms。最优阶段${opt ? '会运行' : '没有运行：根下界已等于当前最优'}。${r.proven ? '已证明最优。' : `在${r.capped_in === 'optimal' ? '最优' : r.capped_in}阶段被截断：保留当前最优，未证明。`}`);
        ghost = null;
      } else {
        const e = E[ev];
        evEl.innerHTML = `${ev + 1}/${E.length} · ${evTextOf(e)}`;
        ghost = e[4] ? e[4].slice() : [];
        if (e[2] >= 0 && e[2] !== vi) { vi = e[2]; varBtns.forEach((b) => b.setAttribute('aria-pressed', String(+b.dataset.var === vi))); }
      }
      drawMeter(); drawDag(); drawOrder(); drawHist(); drawRead();
    }
    function stopReplay() { if (evTimer) { clearInterval(evTimer); evTimer = null; } replayBtn.innerHTML = bi('▶ Replay', '▶ 回放'); }
    function rstep() {
      const E = evList();
      if (ev >= E.length - 1) { ev = -1; ghost = null; showEv(); return false; }
      ev++; showEv(); return true;
    }
    function runReplay() {
      if (evTimer) { stopReplay(); return; }
      ev = -1; order = [];
      if (reduceMotion) { ev = evList().length - 1; showEv(); return; }
      replayBtn.innerHTML = bi('Pause', '暂停');
      evTimer = setInterval(() => { if (!rstep() || ev >= evList().length - 1) stopReplay(); }, 260);
    }

    // ---------- top level ----------
    function render() { drawDag(); drawHist(); drawOrder(); drawRead(); }
    function setSite(k) {
      stopReplay();
      key = k; vi = 0; order = []; ghost = null; ev = -1;
      siteBtns.forEach((b) => b.setAttribute('aria-pressed', String(b.dataset.site === k)));
      varBtns.forEach((b) => b.setAttribute('aria-pressed', String(b.dataset.var === '0')));
      siteEl.innerHTML = SITE[k];
      showEv();
    }
    function preset(nm) {
      stopReplay(); ev = -1; ghost = null;
      const P = prep(key), s = P.s;
      if (nm === 'exact' || nm === 'best' || nm === 'greedy') {
        const x = s.named[nm];
        if (!x) return;
        vi = x.v; order = x.order.slice();
        varBtns.forEach((b) => b.setAttribute('aria-pressed', String(+b.dataset.var === vi)));
      } else if (nm === 'worst') {
        const V = P.vars[vi]; order = V.orders[V.imax].slice();
      }
      showEv();
    }
    siteBtns.forEach((b) => b.addEventListener('click', () => setSite(b.dataset.site)));
    varBtns.forEach((b) => b.addEventListener('click', () => {
      stopReplay(); ev = -1; ghost = null;
      vi = +b.dataset.var;
      varBtns.forEach((x) => x.setAttribute('aria-pressed', String(x === b)));
      if (order.length && !replay(order)) order = [];
      showEv();
    }));
    $$('[data-order]', host).forEach((b) => b.addEventListener('click', () => preset(b.dataset.order)));
    $('[data-act="undo"]', host).addEventListener('click', () => { stopReplay(); ev = -1; ghost = null; order.pop(); showEv(); });
    $('[data-act="clear"]', host).addEventListener('click', () => { stopReplay(); ev = -1; ghost = null; order = []; showEv(); });
    replayBtn.addEventListener('click', runReplay);
    $('[data-act="rstep"]', host).addEventListener('click', () => { stopReplay(); if (ev < 0) order = []; rstep(); });
    setSite('tile');
  }

  const host = document.getElementById('alg1');
  if (host) initExplorer(host);
})();
